# Generated by Django 2.2.6 on 2021-03-14 20:53
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("supply_chains", "0004_auto_20210315_0223"),
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="externaltransaction",
            name="destination_wallet",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incoming_transactions",
                to="supply_chains.BlockchainWallet",
            ),
        ),
        migrations.AddField(
            model_name="externaltransaction",
            name="source_wallet",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outgoing_transactions",
                to="supply_chains.BlockchainWallet",
            ),
        ),
        migrations.AddField(
            model_name="internaltransaction",
            name="node_walet",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="internaltransactions",
                to="supply_chains.BlockchainWallet",
            ),
        ),
        migrations.AddField(
            model_name="sourcebatch",
            name="blockchain_id",
            field=models.CharField(default="", max_length=500),
        ),
        migrations.AddField(
            model_name="transaction",
            name="blockchain_id",
            field=models.CharField(default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="internaltransaction",
            name="node",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="internaltransactions",
                to="supply_chains.Node",
            ),
        ),
    ]
