# Generated by Django 2.2.6 on 2021-04-04 18:15
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0003_externaltransaction_submit_message_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="info_message_address",
            field=models.CharField(default="", max_length=500),
        ),
        migrations.AddField(
            model_name="transaction",
            name="info_message_id",
            field=models.CharField(default="", max_length=500),
        ),
    ]
