# Generated by Django 2.2.6 on 2021-04-05 11:58
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0005_sourcebatch_submit_message_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="sourcebatch",
            name="info_message_address",
            field=models.CharField(default="", max_length=500),
        ),
        migrations.AddField(
            model_name="sourcebatch",
            name="info_message_id",
            field=models.CharField(default="", max_length=500),
        ),
    ]
