# Generated by Django 2.2.6 on 2021-04-07 06:07
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0006_auto_20210405_1728"),
    ]

    operations = [
        migrations.RenameField(
            model_name="internaltransaction",
            old_name="node_walet",
            new_name="node_wallet",
        ),
    ]
