# Generated by Django 2.2.6 on 2021-04-26 14:54
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0007_auto_20210407_1137"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sourcebatch",
            name="quantity",
            field=models.DecimalField(
                decimal_places=3, default=0.0, max_digits=25
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="_destination_quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                default=0.0,
                max_digits=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="_source_quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                default=None,
                max_digits=25,
                null=True,
            ),
        ),
    ]
