# Generated by Django 2.2.6 on 2021-05-10 20:37
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("blockchain", "0011_auto_20210426_2211"),
        ("transactions", "0008_auto_20210426_2024"),
    ]

    operations = [
        migrations.AddField(
            model_name="internaltransaction",
            name="submit_message_request",
            field=models.OneToOneField(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions_internaltransaction_msg_req",
                to="blockchain.BlockchainRequest",
            ),
        ),
    ]
