# Generated by Django 2.2.6 on 2021-05-21 11:45
import common.library
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0009_internaltransaction_submit_message_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="invoice",
            field=models.FileField(
                blank=True,
                default=None,
                null=True,
                upload_to=common.library._get_file_path,
            ),
        ),
    ]
