# Generated by Django 2.2.6 on 2021-06-14 12:20
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0007_nodecard_status"),
        ("transactions", "0010_transaction_invoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="card",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="projects.NodeCard",
            ),
        ),
    ]
