# Generated by Django 2.2.6 on 2021-06-29 12:45
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0011_transaction_card"),
    ]

    operations = [
        migrations.AddField(
            model_name="externaltransaction",
            name="product_price",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="quality_correction",
            field=models.FloatField(default=100.0),
        ),
    ]
