# Generated by Django 2.2.6 on 2021-08-04 11:02
import datetime

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0012_auto_20210629_1815"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="date",
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
