# Generated by Django 2.2.6 on 2021-08-05 06:17
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0013_auto_20210804_1632"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="transaction_platform",
            field=models.IntegerField(
                choices=[(1, "Web"), (2, "App")], default=1
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="verification_method",
            field=models.IntegerField(
                choices=[(1, "Manual"), (2, "Card")], default=1
            ),
        ),
    ]
