# Generated by Django 2.2.6 on 2021-08-05 15:06
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0014_auto_20210805_1147"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="transaction_platform",
            new_name="client_type",
        ),
    ]
