# Generated by Django 2.2.6 on 2022-07-05 09:37
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0016_auto_20210819_1428"),
    ]

    operations = [
        migrations.AddField(
            model_name="externaltransaction",
            name="buyer_ref_number",
            field=models.CharField(
                blank=True, default="", max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="externaltransaction",
            name="seller_ref_number",
            field=models.CharField(
                blank=True, default="", max_length=200, null=True
            ),
        ),
    ]
