# Generated by Django 2.2.6 on 2023-05-27 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0019_auto_20230119_1451'),
        ('transactions', '0019_transactionattachment'),
    ]

    operations = [
    ]
