# Generated by Django 2.2.6 on 2023-11-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0020_merge_20230527_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='externaltransaction',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
