# Generated by Django 2.2.6 on 2024-02-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0021_externaltransaction_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='internaltransaction',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
