# Generated by Django 2.2.6 on 2024-03-21 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0022_internaltransaction_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
