# Generated by Django 2.2.6 on 2021-03-14 18:05
import common.library
import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
import v2.claims.models
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttachedClaim",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "attached_from",
                    models.IntegerField(
                        choices=[
                            (1, "Directly"),
                            (2, "From Transaction"),
                            (3, "Inherited"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "Pending"),
                            (2, "Approved"),
                            (3, "Rejected"),
                            (4, "Partial"),
                        ],
                        default=1,
                    ),
                ),
                ("note", models.TextField(blank=True, default="", null=True)),
                (
                    "blockchain_address",
                    models.CharField(
                        blank=True, default="", max_length=500, null=True
                    ),
                ),
            ],
            options={
                "ordering": ("-created_on",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AttachedCriterion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "attached_from",
                    models.IntegerField(
                        choices=[
                            (1, "Directly"),
                            (2, "From Transaction"),
                            (3, "Inherited"),
                        ],
                        default=2,
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "Pending"),
                            (2, "Approved"),
                            (3, "Rejected"),
                            (4, "Partial"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "blockchain_address",
                    models.CharField(
                        blank=True, default="", max_length=500, null=True
                    ),
                ),
                (
                    "verification_info",
                    models.TextField(blank=True, default=""),
                ),
                (
                    "evidence",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, null=True
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Attached criteria",
            },
        ),
        migrations.CreateModel(
            name="Claim",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=500)),
                (
                    "description_basic",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "description_full",
                    models.CharField(blank=True, default="", max_length=2000),
                ),
                (
                    "type",
                    models.IntegerField(
                        choices=[(1, "Product"), (2, "Company")], default=1
                    ),
                ),
                (
                    "scope",
                    models.IntegerField(
                        choices=[(1, "Global"), (2, "Local")], default=1
                    ),
                ),
                ("proportional", models.BooleanField(default=True)),
                ("removable", models.BooleanField(default=False)),
                (
                    "inheritable",
                    models.IntegerField(
                        choices=[(1, "All"), (2, "None"), (3, "Product")],
                        default=2,
                    ),
                ),
                (
                    "verified_by",
                    models.IntegerField(
                        choices=[
                            (1, "Second"),
                            (2, "Third"),
                            (3, "System"),
                            (4, "None"),
                        ],
                        default=2,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        default=v2.claims.models.get_reference_number,
                        max_length=16,
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                ("active", models.BooleanField(default=True)),
                ("latest", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("-created_on",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ClaimComment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.TextField(blank=True, default="", null=True),
                ),
            ],
            options={
                "ordering": ("-created_on",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Criterion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(default="", max_length=500)),
                ("description", models.TextField(blank=True, default="")),
                ("is_mandatory", models.BooleanField(default=False)),
                (
                    "verification_type",
                    models.IntegerField(
                        choices=[(1, "System"), (2, "Manual")], default=2
                    ),
                ),
                (
                    "verifier",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "guji_traceable",
                                "Traceable Guji Region Verifier",
                            ),
                            ("good_price", "Good Price Verifier"),
                        ],
                        default=None,
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "method",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "Other"), (2, "Map")],
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        default=v2.claims.models.get_reference_number,
                        max_length=16,
                    ),
                ),
                ("version", models.IntegerField(default=1)),
            ],
            options={
                "verbose_name_plural": "Criteria",
            },
        ),
        migrations.CreateModel(
            name="CriterionField",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "options",
                    models.CharField(
                        blank=True, default="", max_length=1000, null=True
                    ),
                ),
                ("multiple_options", models.BooleanField(default=False)),
                (
                    "type",
                    models.IntegerField(
                        choices=[(1, "Text"), (2, "Option"), (3, "File")],
                        default=1,
                    ),
                ),
            ],
            options={
                "ordering": ("created_on",),
            },
        ),
        migrations.CreateModel(
            name="FieldResponse",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("response", models.CharField(max_length=1000)),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to=common.library._get_file_path,
                    ),
                ),
                (
                    "file_hash",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
            ],
            options={
                "ordering": ("-created_on",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AttachedBatchClaim",
            fields=[
                (
                    "attachedclaim_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="claims.AttachedClaim",
                    ),
                ),
                ("verification_percentage", models.FloatField(default=0)),
            ],
            options={
                "ordering": ("-created_on",),
                "abstract": False,
            },
            bases=("claims.attachedclaim", models.Model),
        ),
        migrations.CreateModel(
            name="AttachedBatchCriterion",
            fields=[
                (
                    "attachedcriterion_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="claims.AttachedCriterion",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Attached batch criteria",
            },
            bases=("claims.attachedcriterion",),
        ),
        migrations.CreateModel(
            name="AttachedCompanyClaim",
            fields=[
                (
                    "attachedclaim_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="claims.AttachedClaim",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_on",),
                "abstract": False,
            },
            bases=("claims.attachedclaim",),
        ),
        migrations.CreateModel(
            name="AttachedCompanyCriterion",
            fields=[
                (
                    "attachedcriterion_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="claims.AttachedCriterion",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_on",),
                "abstract": False,
            },
            bases=("claims.attachedcriterion",),
        ),
        migrations.CreateModel(
            name="TransactionClaim",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="claims.Claim",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="creator_transactionclaim_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_on",),
                "abstract": False,
            },
        ),
    ]
