# Generated by Django 2.2.6 on 2021-04-04 18:13
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("claims", "0003_auto_20210315_0223"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachedclaim",
            name="block_chain_request",
            field=models.OneToOneField(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="claims_attachedclaim_msg_req",
                to="blockchain.BlockchainRequest",
            ),
        ),
    ]
