# Generated by Django 2.2.6 on 2022-06-03 07:32
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("claims", "0006_auto_20220601_1514"),
    ]

    operations = [
        migrations.AddField(
            model_name="claim",
            name="description_basic_en",
            field=models.CharField(
                blank=True, default="", max_length=500, null=True
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="description_basic_es",
            field=models.CharField(
                blank=True, default="", max_length=500, null=True
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="description_basic_fr",
            field=models.CharField(
                blank=True, default="", max_length=500, null=True
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="description_basic_nl",
            field=models.CharField(
                blank=True, default="", max_length=500, null=True
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="description_full_en",
            field=models.CharField(
                blank=True, default="", max_length=2000, null=True
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="description_full_es",
            field=models.CharField(
                blank=True, default="", max_length=2000, null=True
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="description_full_fr",
            field=models.CharField(
                blank=True, default="", max_length=2000, null=True
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="description_full_nl",
            field=models.CharField(
                blank=True, default="", max_length=2000, null=True
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="name_en",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="claim",
            name="name_es",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="claim",
            name="name_fr",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="claim",
            name="name_nl",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
