# Generated by Django 2.2.6 on 2022-06-13 12:39
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("claims", "0007_auto_20220603_1302"),
    ]

    operations = [
        migrations.AddField(
            model_name="criterionfield",
            name="options_en",
            field=models.CharField(
                blank=True, default="", max_length=1000, null=True
            ),
        ),
        migrations.AddField(
            model_name="criterionfield",
            name="options_es",
            field=models.CharField(
                blank=True, default="", max_length=1000, null=True
            ),
        ),
        migrations.AddField(
            model_name="criterionfield",
            name="options_fr",
            field=models.CharField(
                blank=True, default="", max_length=1000, null=True
            ),
        ),
        migrations.AddField(
            model_name="criterionfield",
            name="options_nl",
            field=models.CharField(
                blank=True, default="", max_length=1000, null=True
            ),
        ),
        migrations.AddField(
            model_name="criterionfield",
            name="title_en",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="criterionfield",
            name="title_es",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="criterionfield",
            name="title_fr",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="criterionfield",
            name="title_nl",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
