# Generated by Django 2.2.6 on 2022-06-14 04:43
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("claims", "0008_auto_20220613_1809"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="criterionfield",
            name="options_en",
        ),
        migrations.RemoveField(
            model_name="criterionfield",
            name="options_es",
        ),
        migrations.RemoveField(
            model_name="criterionfield",
            name="options_fr",
        ),
        migrations.RemoveField(
            model_name="criterionfield",
            name="options_nl",
        ),
        migrations.AddField(
            model_name="fieldresponse",
            name="response_en",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="fieldresponse",
            name="response_es",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="fieldresponse",
            name="response_fr",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="fieldresponse",
            name="response_nl",
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
