# Generated by Django 2.2.6 on 2022-10-05 07:05

import common.library
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0009_auto_20220614_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=common.library._get_file_path),
        ),
    ]
