# Generated by Django 2.2.6 on 2023-09-26 17:24

import common.library
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0010_claim_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='icon',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=common.library._get_file_path),
        ),
    ]
