# Generated by Django 2.2.6 on 2025-06-14 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('claims', '0012_remove_claim_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='claim_processor',
            field=models.CharField(choices=[('trace', 'Trace'), ('guardian', 'Guardian')], default='trace', max_length=50),
        ),
        migrations.AddField(
            model_name='claim',
            name='key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='GuardianClaim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('hash_value', models.CharField(max_length=200)),
                ('mint_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('extra_info', models.TextField(blank=True, default='')),
                ('company_claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guardian_claims', to='claims.AttachedCompanyClaim')),
                ('creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_guardianclaim_objects', to=settings.AUTH_USER_MODEL)),
                ('trans_claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guardian_claims', to='claims.AttachedBatchClaim')),
                ('updater', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater_guardianclaim_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
    ]
