# Generated by Django 2.2.6 on 2022-01-03 04:28
import common.library
import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("supply_chains", "0020_auto_20211118_1445"),
    ]

    operations = [
        migrations.CreateModel(
            name="NodeTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "Active"), (2, "Inactive")], default=2
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="creator_nodetemplate_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="node_template",
                        to="supply_chains.Node",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_on",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=100)),
                ("title_row", models.CharField(default="", max_length=500)),
                ("data_row", models.CharField(default="", max_length=500)),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=common.library._get_file_path,
                    ),
                ),
                (
                    "type",
                    models.IntegerField(
                        choices=[(1, "Transaction"), (2, "Connection")],
                        default=1,
                    ),
                ),
                (
                    "visibility",
                    models.IntegerField(
                        choices=[(1, "Public"), (2, "Private"), (3, "Hidden")],
                        default=3,
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="creator_template_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "nodes",
                    models.ManyToManyField(
                        related_name="templates",
                        through="bulk_templates.NodeTemplate",
                        to="supply_chains.Node",
                    ),
                ),
                (
                    "updater",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updater_template_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_on",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TemplateTypeField",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("required", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=500)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=1000),
                ),
                (
                    "template_type",
                    models.IntegerField(
                        choices=[(1, "Transaction"), (2, "Connection")],
                        default=1,
                    ),
                ),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (1, "Farmer Id"),
                            (2, "Latitude"),
                            (3, "String"),
                            (4, "Integer"),
                            (5, "Float"),
                            (6, "Date"),
                            (7, "Phone"),
                            (8, "Email"),
                            (9, "Trace Id"),
                        ],
                        default=3,
                    ),
                ),
                (
                    "meta",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, default=dict, null=True
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="creator_templatetypefield_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "optional_with",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bulk_templates.TemplateTypeField",
                    ),
                ),
                (
                    "updater",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updater_templatetypefield_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_on",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TemplateField",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("column_pos", models.CharField(max_length=100)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="creator_templatefield_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_fields",
                        to="bulk_templates.TemplateTypeField",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_fields",
                        to="bulk_templates.Template",
                    ),
                ),
                (
                    "updater",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updater_templatefield_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_on",),
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="nodetemplate",
            name="template",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="node_templates",
                to="bulk_templates.Template",
            ),
        ),
        migrations.AddField(
            model_name="nodetemplate",
            name="updater",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updater_nodetemplate_objects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
