# Generated by Django 2.2.6 on 2022-01-04 04:04
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("supply_chains", "0020_auto_20211118_1445"),
        ("bulk_templates", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DynamicBulkUpload",
            fields=[
                (
                    "bulkexceluploads_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="supply_chains.BulkExcelUploads",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bulk_template",
                        to="bulk_templates.Template",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_on",),
                "abstract": False,
            },
            bases=("supply_chains.bulkexceluploads",),
        ),
    ]
