# Generated by Django 2.2.6 on 2022-01-12 15:56
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("bulk_templates", "0002_dynamicbulkupload"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="templatetypefield",
            options={},
        ),
        migrations.AddField(
            model_name="templatetypefield",
            name="key",
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="templatetypefield",
            name="span",
            field=models.IntegerField(
                choices=[(1, "Half span"), (2, "Full span")], default=1
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="data_row",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="template",
            name="title_row",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="templatefield",
            name="field",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="template_field",
                to="bulk_templates.TemplateTypeField",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="templatetypefield",
            unique_together={("name", "key")},
        ),
    ]
