# Generated by Django 2.2.6 on 2022-01-13 10:16
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("bulk_templates", "0003_auto_20220112_2126"),
    ]

    operations = [
        migrations.AlterField(
            model_name="templatefield",
            name="column_pos",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="templatetypefield",
            name="type",
            field=models.IntegerField(
                choices=[
                    (1, "Farmer Id"),
                    (2, "Latitude"),
                    (3, "String"),
                    (4, "Integer"),
                    (5, "Float"),
                    (6, "Date"),
                    (7, "Phone"),
                    (8, "Email"),
                    (9, "Trace Id"),
                    (10, "Currency"),
                ],
                default=3,
            ),
        ),
    ]
