# Generated by Django 2.2.6 on 2022-03-03 12:38
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("bulk_templates", "0005_auto_20220221_1141"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
