# Generated by Django 2.2.6 on 2022-06-01 09:44
import v2.bulk_templates.models
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("bulk_templates", "0007_auto_20220307_1033"),
    ]

    operations = [
        migrations.AlterField(
            model_name="template",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=v2.bulk_templates.models._get_file_path,
            ),
        ),
    ]
