# Generated by Django 2.2.6 on 2023-08-05 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_uploads', '0005_auto_20230725_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasheetupload',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
