# Generated by Django 2.2.6 on 2023-08-09 07:43

import common.library
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_uploads', '0006_datasheetupload_is_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasheetupload',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=common.library.DateTimeEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='datasheetupload',
            name='initial_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=common.library.DateTimeEncoder, null=True),
        ),
    ]
