# Generated by Django 2.2.6 on 2023-08-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_uploads', '0007_auto_20230809_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasheetuploadsummary',
            name='average_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datasheetuploadsummary',
            name='highest_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datasheetuploadsummary',
            name='lowest_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datasheetuploadsummary',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datasheetuploadsummary',
            name='total_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
