# Generated by Django 2.2.6 on 2023-08-14 10:20

from django.db import migrations, models
import v2.bulk_uploads.models.common


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_uploads', '0009_auto_20230811_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasheettemplate',
            name='file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=v2.bulk_uploads.models.common.get_file_path),
        ),
    ]
