# Generated by Django 2.2.6 on 2023-08-14 10:23

from django.db import migrations, models
import v2.bulk_uploads.models.common


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_uploads', '0010_auto_20230814_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasheetupload',
            name='file',
            field=models.FileField(max_length=255, upload_to=v2.bulk_uploads.models.common.get_file_path),
        ),
    ]
