# Generated by Django 2.2.6 on 2023-08-17 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chains', '0039_company_make_farmers_private'),
        ('bulk_uploads', '0011_auto_20230814_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasheettemplate',
            name='supply_chain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supply_chains.SupplyChain'),
        ),
        migrations.AddField(
            model_name='datasheetupload',
            name='supply_chain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supply_chains.SupplyChain'),
        ),
    ]
