# Generated by Django 2.2.6 on 2025-04-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_uploads', '0015_auto_20240205_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasheettemplate',
            name='unit',
            field=models.IntegerField(blank=True, choices=[(1, 'KG'), (2, 'Tonne'), (3, 'Metric Ton of CO2e')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='datasheetupload',
            name='unit',
            field=models.IntegerField(blank=True, choices=[(1, 'KG'), (2, 'Tonne'), (3, 'Metric Ton of CO2e')], default=1, null=True),
        ),
    ]
