# Generated by Django 2.2.6 on 2025-06-04 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0024_auto_20250408_1258'),
        ('bulk_uploads', '0016_auto_20250408_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasheetupload',
            name='added_transactions',
            field=models.ManyToManyField(related_name='datasheet_uploads', to='transactions.Transaction'),
        ),
    ]
