exclude: migrations/
repos:
  - repo: local
    hooks:
      - id: commit-msg-validator
        name: commit-msg-validator
        entry: python .githooks/commit-msg.py
        language: python
        pass_filenames: false
        stages: [ commit-msg ]
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        args: [ --line-length=79 ]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-byte-order-marker

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
      - id: reorder-python-imports
  - repo: https://gitlab.com/pycqa/flake8
    rev: '3.9.2'
    hooks:
      - id: flake8
        exclude: ^migrations/
        args: [ "--config=setup.cfg" ]
        language_version: python3

  - repo: local
    hooks:
      - id: system
        name: pytype
        entry: bash -c "pytype fairtrace_v2 --config=pytype.cfg"
        language: system
        pass_filenames: false
  - repo: local
    hooks:
      - id: migrations-check
        language: system
        name: Check for uncreated migrations.
        entry: bash -c "./fairtrace_v2/manage.py makemigrations --check --dry-run"
        types: [ "python" ]
        pass_filenames: false
#  - repo: https://github.com/mattseymour/pre-commit-pytype
#    rev: '2022.4.26'
#    hooks:
#      - id: pytype
#        # entry: pytype  --config=pytype.cfg
#        args: [ "--config=pytype.cfg", "--exclude=.pytype/" ]
  - repo: https://github.com/PyCQA/docformatter
    rev: 'v1.5.0'
    hooks:
      - id: docformatter
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle
        args: [ "--count", "--select=D101,D102, D103" ]
        exclude: (tests|fabfile)/
