# Generated by Django 2.2.6 on 2021-04-26 14:54
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("transparency_request", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockrequest",
            name="quantity",
            field=models.DecimalField(
                decimal_places=3, default=0.0, max_digits=25
            ),
        ),
    ]
