# Generated by Django 2.2.6 on 2025-04-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transparency_request', '0002_auto_20210426_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockrequest',
            name='unit',
            field=models.IntegerField(choices=[(1, 'KG'), (2, 'Tonne'), (3, 'Metric Ton of CO2e')], default=1),
        ),
    ]
