# Generated by Django 2.2.6 on 2021-05-16 09:41
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectpremium",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="premiums",
                to="projects.Project",
            ),
            preserve_default=False,
        ),
    ]
