# Generated by Django 2.2.6 on 2021-06-02 08:06
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_premiumearned"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectnode",
            name="connection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="supply_chains.Connection",
            ),
        ),
    ]
