# Generated by Django 2.2.6 on 2021-06-14 11:44
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0006_projectproduct_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="nodecard",
            name="status",
            field=models.IntegerField(
                choices=[
                    (101, "Active"),
                    (201, "Inactive"),
                    (301, "Lost"),
                    (401, "Blocked"),
                ],
                default=101,
            ),
        ),
    ]
