# Generated by Django 2.2.6 on 2021-06-25 11:52
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0008_project_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="buy_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="project",
            name="quality_correction",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="sell_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="show_price_comparison",
            field=models.BooleanField(default=True),
        ),
    ]
