# Generated by Django 2.2.6 on 2021-10-13 07:11
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0009_auto_20210625_1722"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectpremium",
            name="applicable_activity",
            field=models.IntegerField(
                choices=[(101, "Activity buy"), (201, "Activity sell")],
                default=101,
            ),
        ),
    ]
