# Generated by Django 2.2.6 on 2021-10-27 12:31
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0010_projectpremium_applicable_activity"),
    ]

    operations = [
        migrations.AddField(
            model_name="nodecard",
            name="fairid",
            field=models.CharField(default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="nodecard",
            name="card_id",
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name="nodecard",
            name="node",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cards",
                to="supply_chains.Node",
            ),
        ),
    ]
