# Generated by Django 2.2.6 on 2022-06-23 08:58
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0011_auto_20211027_1801"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectproduct",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="projectproduct",
            name="premiums",
            field=models.ManyToManyField(to="projects.ProjectPremium"),
        ),
    ]
