# Generated by Django 2.2.6 on 2023-04-04 07:27
from django.db import migrations, models
import django.db.models.deletion

from v2.supply_chains.constants import TRACE_FARMER_REFERENCE_NAME, \
    NODE_TYPE_FARM


def create_references(apps, schema_editor):
    """Update NodeCard against FramerReference.  """
    # create initial reference item for farmer card.
    reference_model = apps.get_model('supply_chains', 'Reference')
    reference_model.objects.create(name=TRACE_FARMER_REFERENCE_NAME,
                                   description='Trace farmer card',
                                   is_editable=False)

    node_card_model = apps.get_model('projects', 'NodeCard')
    node_cards = node_card_model.objects.all()
    for node_card in node_cards:
        if node_card.node and node_card.node.type == NODE_TYPE_FARM:
            _create_reference(apps, node_card, reference_model)
            node_card.save()


def _create_reference(apps, card, reference_model):
    name_string = TRACE_FARMER_REFERENCE_NAME
    farmer_reference_model = apps.get_model('supply_chains', 'FarmerReference')
    ref = reference_model.objects.get(name__iexact=name_string)
    # create farmer reference
    card.reference = farmer_reference_model.objects.create(
        reference_id=ref.id, farmer_id=card.node_id,
        number=card.fairid or card.card_id)


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chains', '0030_farmerreference_reference'),
        ('projects', '0015_auto_20230328_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodecard',
            name='reference',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farmer_reference', to='supply_chains.FarmerReference'),
        ),
        migrations.RunPython(create_references)
    ]
