# Generated by Django 2.2.6 on 2023-04-10 05:47

from django.db import migrations, models


# def initialize(apps, scheme):
#     payment_model = apps.get_model('projects', 'Payment')
#     objs = []
#     for payment in payment_model.objects.all():
#         if payment.source and payment.destination:
#             payment_str = payment.premium.name if payment.premium else 'Base price'
#             payment.description = (f' {payment.source.full_name} paid '
#                                    f'{payment_str} to '
#                                    f'{payment.destination.full_name}')
#             if payment.transaction and payment.transaction.product:
#                 payment.description += (f' for product '
#                                         f'{payment.transaction.product.name}')
#             objs.append(payment)
#     payment_model.objects.bulk_update(objs, fields=['description'])


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20230406_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
