# Generated by Django 2.2.6 on 2023-05-26 07:22

from django.db import migrations
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_payment_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='extra_fields',
            field=django_extensions.db.fields.json.JSONField(blank=True, default=dict, null=True),
        ),
    ]
