# Generated by Django 2.2.6 on 2023-06-14 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import v2.projects.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0019_payment_extra_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='slab',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='projectpremium',
            name='calculation_type',
            field=models.CharField(choices=[('NORMAL', 'NORMAL'), ('MANUAL', 'MANUAL'), ('SLABS_WITH_RANGE', 'SLABS_WITH_RANGE'), ('SLABS', 'SLABS')], default='NORMAL', max_length=20),
        ),
        migrations.CreateModel(
            name='PremiumSlab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('slab', models.CharField(max_length=25, validators=[v2.projects.models.validate_premium_slab])),
                ('amount', models.FloatField()),
                ('creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_premiumslab_objects', to=settings.AUTH_USER_MODEL)),
                ('premium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.ProjectPremium')),
                ('updater', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater_premiumslab_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
    ]
