# Generated by Django 2.2.6 on 2023-06-14 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_auto_20230614_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpremium',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
