# Generated by Django 2.2.6 on 2023-07-06 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0022_projectpremium_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=25)),
                ('amount', models.FloatField()),
                ('creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_premiumoption_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='payment',
            name='slab',
        ),
        migrations.AlterField(
            model_name='projectpremium',
            name='calculation_type',
            field=models.CharField(choices=[('NORMAL', 'NORMAL'), ('MANUAL', 'MANUAL'), ('OPTIONS', 'OPTIONS')], default='NORMAL', max_length=20),
        ),
        migrations.DeleteModel(
            name='PremiumSlab',
        ),
        migrations.AddField(
            model_name='premiumoption',
            name='premium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slabs', to='projects.ProjectPremium'),
        ),
        migrations.AddField(
            model_name='premiumoption',
            name='updater',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater_premiumoption_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='selected_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.PremiumOption'),
        ),
    ]
