# Generated by Django 2.2.6 on 2023-11-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_payment_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpremium',
            name='external_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
