# Generated by Django 2.2.6 on 2023-11-29 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_projectpremium_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodecard',
            name='external_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
