# Generated by Django 2.2.6 on 2024-06-11 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chains', '0049_node_navigate_id'),
        ('projects', '0029_synchronization'),
    ]

    operations = [
        migrations.AddField(
            model_name='synchronization',
            name='node',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='syncs', to='supply_chains.Node'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='synchronization',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'IN_PROGRESS'), ('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED')], default='IN_PROGRESS', max_length=15),
        ),
        migrations.AddField(
            model_name='synchronization',
            name='supply_chain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='syncs', to='supply_chains.SupplyChain'),
        ),
    ]
