# Generated by Django 2.2.6 on 2025-02-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_auto_20240611_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodecard',
            name='card_id',
            field=models.CharField(max_length=500),
        ),
    ]
