"""Constants for Blockchain APP."""
# Middleware actions
ACTION_CREATE_ACCOUNT = 1
ACTION_CREATE_TOKEN = 2
ACTION_ASSOCIATE_TOKEN = 3
ACTION_KYC_TOKEN = 4
ACTION_TOKEN_TRANSFER = 5
ACTION_HBAR_TRANSFER = 6
ACTION_CREATE_TOPIC = 7
ACTION_CREATE_CONSENSUS = 8

# Initial Balance
INITIAL_BALANCE = 2
HBAR_MINIMUM_BALANCE = 0.1
HBAR_RECHARGE_AMOUNT = 1

# CB Token Status
CBTOKEN_STATUS_UNUSED = 1
CBTOKEN_STATUS_USED = 2
CBTOKEN_STATUS_INVALIDATED = 3

CBTOKEN_STATUS_CHOICES = (
    (CBTOKEN_STATUS_UNUSED, "Unused"),
    (CBTOKEN_STATUS_USED, "Used"),
    (CBTOKEN_STATUS_INVALIDATED, "Invalidated"),
)

# CB Token Validity
TOKEN_VALIDITY = {"days": 30}

# Time to wait until the request could be discarded
REQUEST_DELAY_TOLERENCE = {"hours": 12}

# Blockchain Request statuses
BC_REQUEST_STATUS_PENDING = 1
BC_REQUEST_STATUS_COMPLETED = 2
BC_REQUEST_STATUS_DISCARDED = 3  # When the request is no longer required o
BC_REQUEST_STATUS_FAILED = 4

BC_REQUEST_STATUS_CHOICES = (
    (BC_REQUEST_STATUS_PENDING, "Pending"),
    (BC_REQUEST_STATUS_COMPLETED, "Completed"),
    (BC_REQUEST_STATUS_DISCARDED, "Discarded"),
    (BC_REQUEST_STATUS_FAILED, "Failed"),
)

HEDERA_CONSENSUS_MESSAGE_SIZE = 6000
