# Generated by Django 2.2.6 on 2022-11-11 02:58

import common.library
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supply_chains', '0028_farmer_extra_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('export_type', models.IntegerField(choices=[(1, 'Batch')])),
                ('file', models.FileField(blank=True, null=True, upload_to=common.library._get_file_path)),
                ('file_name', models.CharField(blank=True, max_length=50, null=True)),
                ('task_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('completed', models.BooleanField(default=False)),
                ('filters', django_extensions.db.fields.json.JSONField(default=dict)),
                ('rows', models.IntegerField(default=0)),
                ('etc', models.PositiveIntegerField(default=0)),
                ('atc', models.PositiveIntegerField(default=0)),
                ('revoked', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_export_objects', to=settings.AUTH_USER_MODEL)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply_chains.Node')),
                ('updater', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater_export_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
    ]
