# Generated by Django 2.2.6 on 2022-11-11 03:06

from django.db import migrations
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='export',
            name='filters',
            field=django_extensions.db.fields.json.JSONField(blank=True, default=dict, null=True),
        ),
    ]
