# Generated by Django 2.2.6 on 2022-11-11 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20221111_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='export',
            name='file_type',
            field=models.IntegerField(choices=[(1, '.xlsx'), (2, '.csv')], default=1),
        ),
        migrations.AlterField(
            model_name='export',
            name='export_type',
            field=models.IntegerField(choices=[(1, 'STOCK'), (2, 'EXTERNAL_TRANSACTION'), (3, 'INTERNAL_TRANSACTION'), (4, 'CONNECTIONS'), (5, 'FARMER'), (4, 'COMPANY')]),
        ),
    ]
