# Generated by Django 2.2.6 on 2022-12-03 17:42

import common.library
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20221111_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='export',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=common.library.get_file_path_without_random),
        ),
    ]
