# Generated by Django 2.2.6 on 2022-12-07 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20221203_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='export',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='export',
            name='revoked',
        ),
        migrations.AddField(
            model_name='export',
            name='status',
            field=models.CharField(choices=[('PEND', 'PENDING'), ('DONE', 'COMPLETED'), ('RVKD', 'REVOKED'), ('FAIL', 'FAILED')], default='PEND', max_length=4),
        ),
        migrations.AlterField(
            model_name='export',
            name='export_type',
            field=models.IntegerField(choices=[(1, 'STOCK'), (2, 'EXTERNAL_TRANSACTION'), (3, 'INTERNAL_TRANSACTION'), (4, 'CONNECTIONS'), (5, 'FARMER'), (6, 'COMPANY')]),
        ),
    ]
