# Generated by Django 2.2.6 on 2023-04-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_auto_20230112_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='export',
            name='export_type',
            field=models.IntegerField(choices=[(1, 'STOCK'), (2, 'EXTERNAL_TRANSACTION'), (3, 'INTERNAL_TRANSACTION'), (4, 'CONNECTIONS'), (5, 'FARMER'), (6, 'COMPANY'), (7, 'ADMIN_COMPANY'), (8, 'ADMIN_FARMER'), (9, 'ADMIN_EXTERNAL_TRANSACTION'), (10, 'PAYMENTS')]),
        ),
    ]
