CUSTOM_TEMP_NAME = "Data Sheet Template"

TEMPLATE_TYPE_TXN = 1
TEMPLATE_TYPE_CONNECTION = 2

TEMPLATE_TYPE_CHOICES = (
    (TEMPLATE_TYPE_TXN, "Transaction"),
    (TEMPLATE_TYPE_CONNECTION, "Connection"),
)

TEMPLATE_VISIBILITY_PUBLIC = 1
TEMPLATE_VISIBILITY_PRIVATE = 2
TEMPLATE_VISIBILITY_HIDDEN = 3

TEMPLATE_VISIBILITY_CHOICES = (
    (TEMPLATE_VISIBILITY_PUBLIC, "Public"),
    (TEMPLATE_VISIBILITY_PRIVATE, "Private"),
    (TEMPLATE_VISIBILITY_HIDDEN, "Hidden"),
)

NODE_TEMPLATE_STATUS_ACTIVE = 1
NODE_TEMPLATE_STATUS_INACTIVE = 2

NODE_TEMPLATE_STATUS_CHOICES = (
    (NODE_TEMPLATE_STATUS_ACTIVE, "Active"),
    (NODE_TEMPLATE_STATUS_INACTIVE, "Inactive"),
)
