# Generated by Django 2.2.6 on 2021-03-14 20:53
import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("blockchain", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssociateTokenRequest",
            fields=[
                (
                    "blockchainrequest_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="blockchain.BlockchainRequest",
                    ),
                ),
            ],
            bases=("blockchain.blockchainrequest",),
        ),
        migrations.CreateModel(
            name="CallbackResponse",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("success", models.BooleanField(default=False)),
                (
                    "data",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        default=dict
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CreateTokenRequest",
            fields=[
                (
                    "blockchainrequest_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="blockchain.BlockchainRequest",
                    ),
                ),
            ],
            bases=("blockchain.blockchainrequest",),
        ),
        migrations.CreateModel(
            name="KYCTokenRequest",
            fields=[
                (
                    "blockchainrequest_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="blockchain.BlockchainRequest",
                    ),
                ),
            ],
            bases=("blockchain.blockchainrequest",),
        ),
        migrations.CreateModel(
            name="SubmitMessageRequest",
            fields=[
                (
                    "blockchainrequest_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="blockchain.BlockchainRequest",
                    ),
                ),
            ],
            bases=("blockchain.blockchainrequest",),
        ),
        migrations.CreateModel(
            name="TransferHBARRequest",
            fields=[
                (
                    "blockchainrequest_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="blockchain.BlockchainRequest",
                    ),
                ),
            ],
            bases=("blockchain.blockchainrequest",),
        ),
    ]
