# Generated by Django 2.2.6 on 2021-03-14 20:53
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("supply_chains", "0004_auto_20210315_0223"),
        ("transactions", "0002_auto_20210315_0223"),
        (
            "blockchain",
            "0002_associatetokenrequest_callbackresponse_createtokenrequest_kyctokenrequest_submitmessagerequest_trans",
        ),
        ("products", "0003_auto_20210315_0223"),
        ("claims", "0003_auto_20210315_0223"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BurnAssetRequest",
            new_name="BurnTokenRequest",
        ),
        migrations.RenameModel(
            old_name="CreateKeyRequest",
            new_name="CreateAccountRequest",
        ),
        migrations.RenameModel(
            old_name="CreateAssetRequest",
            new_name="MintTokenRequest",
        ),
        migrations.RenameModel(
            old_name="TransferAssetRequest",
            new_name="TransferTokenRequest",
        ),
        migrations.AddField(
            model_name="callbackresponse",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="blockchain.BlockchainRequest",
            ),
        ),
    ]
