# Generated by Django 2.2.6 on 2021-03-15 08:43
import v2.blockchain.models.request
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("blockchain", "0004_blockchainrequest_response"),
    ]

    operations = [
        migrations.AddField(
            model_name="blockchainrequest",
            name="request_password",
            field=models.CharField(
                default=v2.blockchain.models.request.get_request_password,
                max_length=200,
            ),
        ),
    ]
