# Generated by Django 2.2.6 on 2021-03-18 15:03
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("blockchain", "0005_blockchainrequest_request_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blockchainrequest",
            name="status",
            field=models.IntegerField(
                choices=[(1, "Pending"), (2, "Completed"), (3, "Discarded")],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="callbacktoken",
            name="status",
            field=models.IntegerField(
                choices=[(1, "Unused"), (2, "Used"), (3, "Invalidated")],
                default=1,
            ),
        ),
    ]
