# Generated by Django 2.2.6 on 2021-03-22 07:14
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("blockchain", "0006_auto_20210318_2033"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blockchainrequest",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "Pending"),
                    (2, "Completed"),
                    (3, "Discarded"),
                    (4, "Failed"),
                ],
                default=1,
            ),
        ),
    ]
