# Generated by Django 2.2.6 on 2021-04-03 10:21
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blockchain", "0007_auto_20210322_1244"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blockchainrequest",
            old_name="request_password",
            new_name="password",
        ),
    ]
