# Generated by Django 2.2.6 on 2021-04-19 17:53
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blockchain", "0008_auto_20210403_1551"),
    ]

    operations = [
        migrations.AddField(
            model_name="blockchainrequest",
            name="body",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
