# Generated by Django 2.2.6 on 2021-04-21 17:17
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("blockchain", "0009_blockchainrequest_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="blockchainrequest",
            name="last_api_call",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
