# Generated by Django 2.2.6 on 2021-04-26 16:41
import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blockchain", "0010_blockchainrequest_last_api_call"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blockchainrequest",
            name="body",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
            ),
        ),
        migrations.AlterField(
            model_name="blockchainrequest",
            name="response",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
            ),
        ),
        migrations.AlterField(
            model_name="callbackresponse",
            name="data",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
            ),
        ),
    ]
