# Generated by Django 2.2.6 on 2022-06-01 05:00
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0002_auto_20210314_2335"),
    ]

    operations = [
        migrations.AddField(
            model_name="citheme",
            name="available_languages",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
