# Generated by Django 2.2.6 on 2022-06-01 11:27
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0003_citheme_available_languages"),
    ]

    operations = [
        migrations.AddField(
            model_name="citheme",
            name="action_button_text_en",
            field=models.CharField(
                blank=True, default="", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="citheme",
            name="action_button_text_es",
            field=models.CharField(
                blank=True, default="", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="citheme",
            name="action_button_text_fr",
            field=models.CharField(
                blank=True, default="", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="citheme",
            name="action_button_text_nl",
            field=models.CharField(
                blank=True, default="", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="citheme",
            name="banner_text_en",
            field=models.CharField(
                blank=True, default="", max_length=500, null=True
            ),
        ),
        migrations.AddField(
            model_name="citheme",
            name="banner_text_es",
            field=models.CharField(
                blank=True, default="", max_length=500, null=True
            ),
        ),
        migrations.AddField(
            model_name="citheme",
            name="banner_text_fr",
            field=models.CharField(
                blank=True, default="", max_length=500, null=True
            ),
        ),
        migrations.AddField(
            model_name="citheme",
            name="banner_text_nl",
            field=models.CharField(
                blank=True, default="", max_length=500, null=True
            ),
        ),
        migrations.AddField(
            model_name="citheme",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=100, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="citheme",
            name="name_es",
            field=models.CharField(
                blank=True, max_length=100, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="citheme",
            name="name_fr",
            field=models.CharField(
                blank=True, max_length=100, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="citheme",
            name="name_nl",
            field=models.CharField(
                blank=True, max_length=100, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="citheme",
            name="share_facebook_body_en",
            field=models.CharField(
                blank=True, default="", max_length=2000, null=True
            ),
        ),
        migrations.AddField(
            model_name="citheme",
            name="share_facebook_body_es",
            field=models.CharField(
                blank=True, default="", max_length=2000, null=True
            ),
        ),
        migrations.AddField(
            model_name="citheme",
            name="share_facebook_body_fr",
            field=models.CharField(
                blank=True, default="", max_length=2000, null=True
            ),
        ),
        migrations.AddField(
            model_name="citheme",
            name="share_facebook_body_nl",
            field=models.CharField(
                blank=True, default="", max_length=2000, null=True
            ),
        ),
        migrations.AddField(
            model_name="citheme",
            name="share_facebook_title_en",
            field=models.CharField(
                blank=True, default="", max_length=500, null=True
            ),
        ),
        migrations.AddField(
            model_name="citheme",
            name="share_facebook_title_es",
            field=models.CharField(
                blank=True, default="", max_length=500, null=True
            ),
        ),
        migrations.AddField(
            model_name="citheme",
            name="share_facebook_title_fr",
            field=models.CharField(
                blank=True, default="", max_length=500, null=True
            ),
        ),
        migrations.AddField(
            model_name="citheme",
            name="share_facebook_title_nl",
            field=models.CharField(
                blank=True, default="", max_length=500, null=True
            ),
        ),
        migrations.AddField(
            model_name="citheme",
            name="share_linkedin_body_en",
            field=models.CharField(
                blank=True, default="", max_length=2000, null=True
            ),
        ),
        migrations.AddField(
            model_name="citheme",
            name="share_linkedin_body_es",
            field=models.CharField(
                blank=True, default="", max_length=2000, null=True
            ),
        ),
        migrations.AddField(
            model_name="citheme",
            name="share_linkedin_body_fr",
            field=models.CharField(
                blank=True, default="", max_length=2000, null=True
            ),
        ),
        migrations.AddField(
            model_name="citheme",
            name="share_linkedin_body_nl",
            field=models.CharField(
                blank=True, default="", max_length=2000, null=True
            ),
        ),
        migrations.AddField(
            model_name="citheme",
            name="share_linkedin_title_en",
            field=models.CharField(
                blank=True, default="", max_length=500, null=True
            ),
        ),
        migrations.AddField(
            model_name="citheme",
            name="share_linkedin_title_es",
            field=models.CharField(
                blank=True, default="", max_length=500, null=True
            ),
        ),
        migrations.AddField(
            model_name="citheme",
            name="share_linkedin_title_fr",
            field=models.CharField(
                blank=True, default="", max_length=500, null=True
            ),
        ),
        migrations.AddField(
            model_name="citheme",
            name="share_linkedin_title_nl",
            field=models.CharField(
                blank=True, default="", max_length=500, null=True
            ),
        ),
        migrations.AddField(
            model_name="citheme",
            name="share_twitter_body_en",
            field=models.CharField(
                blank=True, default="", max_length=2000, null=True
            ),
        ),
        migrations.AddField(
            model_name="citheme",
            name="share_twitter_body_es",
            field=models.CharField(
                blank=True, default="", max_length=2000, null=True
            ),
        ),
        migrations.AddField(
            model_name="citheme",
            name="share_twitter_body_fr",
            field=models.CharField(
                blank=True, default="", max_length=2000, null=True
            ),
        ),
        migrations.AddField(
            model_name="citheme",
            name="share_twitter_body_nl",
            field=models.CharField(
                blank=True, default="", max_length=2000, null=True
            ),
        ),
        migrations.AddField(
            model_name="citheme",
            name="share_twitter_title_en",
            field=models.CharField(
                blank=True, default="", max_length=500, null=True
            ),
        ),
        migrations.AddField(
            model_name="citheme",
            name="share_twitter_title_es",
            field=models.CharField(
                blank=True, default="", max_length=500, null=True
            ),
        ),
        migrations.AddField(
            model_name="citheme",
            name="share_twitter_title_fr",
            field=models.CharField(
                blank=True, default="", max_length=500, null=True
            ),
        ),
        migrations.AddField(
            model_name="citheme",
            name="share_twitter_title_nl",
            field=models.CharField(
                blank=True, default="", max_length=500, null=True
            ),
        ),
        migrations.AddField(
            model_name="citheme",
            name="share_whatsapp_body_en",
            field=models.CharField(
                blank=True, default="", max_length=2000, null=True
            ),
        ),
        migrations.AddField(
            model_name="citheme",
            name="share_whatsapp_body_es",
            field=models.CharField(
                blank=True, default="", max_length=2000, null=True
            ),
        ),
        migrations.AddField(
            model_name="citheme",
            name="share_whatsapp_body_fr",
            field=models.CharField(
                blank=True, default="", max_length=2000, null=True
            ),
        ),
        migrations.AddField(
            model_name="citheme",
            name="share_whatsapp_body_nl",
            field=models.CharField(
                blank=True, default="", max_length=2000, null=True
            ),
        ),
        migrations.AddField(
            model_name="citheme",
            name="share_whatsapp_title_en",
            field=models.CharField(
                blank=True, default="", max_length=500, null=True
            ),
        ),
        migrations.AddField(
            model_name="citheme",
            name="share_whatsapp_title_es",
            field=models.CharField(
                blank=True, default="", max_length=500, null=True
            ),
        ),
        migrations.AddField(
            model_name="citheme",
            name="share_whatsapp_title_fr",
            field=models.CharField(
                blank=True, default="", max_length=500, null=True
            ),
        ),
        migrations.AddField(
            model_name="citheme",
            name="share_whatsapp_title_nl",
            field=models.CharField(
                blank=True, default="", max_length=500, null=True
            ),
        ),
        migrations.AddField(
            model_name="citheme",
            name="video_description_en",
            field=models.CharField(
                blank=True, default="", max_length=1000, null=True
            ),
        ),
        migrations.AddField(
            model_name="citheme",
            name="video_description_es",
            field=models.CharField(
                blank=True, default="", max_length=1000, null=True
            ),
        ),
        migrations.AddField(
            model_name="citheme",
            name="video_description_fr",
            field=models.CharField(
                blank=True, default="", max_length=1000, null=True
            ),
        ),
        migrations.AddField(
            model_name="citheme",
            name="video_description_nl",
            field=models.CharField(
                blank=True, default="", max_length=1000, null=True
            ),
        ),
        migrations.AddField(
            model_name="citheme",
            name="video_title_en",
            field=models.CharField(
                blank=True, default="", max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="citheme",
            name="video_title_es",
            field=models.CharField(
                blank=True, default="", max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="citheme",
            name="video_title_fr",
            field=models.CharField(
                blank=True, default="", max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="citheme",
            name="video_title_nl",
            field=models.CharField(
                blank=True, default="", max_length=200, null=True
            ),
        ),
        migrations.AlterField(
            model_name="citheme",
            name="available_languages",
            field=models.CharField(
                blank=True, default="en", max_length=500, null=True
            ),
        ),
    ]
