# Generated by Django 2.2.6 on 2022-06-01 11:48
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0004_auto_20220601_1657"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="citheme",
            name="name_en",
        ),
        migrations.RemoveField(
            model_name="citheme",
            name="name_es",
        ),
        migrations.RemoveField(
            model_name="citheme",
            name="name_fr",
        ),
        migrations.RemoveField(
            model_name="citheme",
            name="name_nl",
        ),
    ]
