# Generated by Django 2.2.6 on 2022-06-01 12:49
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0005_auto_20220601_1718"),
    ]

    operations = [
        migrations.AddField(
            model_name="citheme",
            name="brand_name_en",
            field=models.CharField(
                blank=True, default="", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="citheme",
            name="brand_name_es",
            field=models.CharField(
                blank=True, default="", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="citheme",
            name="brand_name_fr",
            field=models.CharField(
                blank=True, default="", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="citheme",
            name="brand_name_nl",
            field=models.CharField(
                blank=True, default="", max_length=100, null=True
            ),
        ),
    ]
