# Generated by Django 2.2.6 on 2022-06-02 05:24
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0006_auto_20220601_1819"),
    ]

    operations = [
        migrations.AddField(
            model_name="citheme",
            name="default_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="citheme",
            name="default_description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="citheme",
            name="default_description_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="citheme",
            name="default_description_fr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="citheme",
            name="default_description_nl",
            field=models.TextField(blank=True, null=True),
        ),
    ]
