# Generated by Django 2.2.6 on 2022-06-03 07:32
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0008_auto_20220602_1142"),
    ]

    operations = [
        migrations.AddField(
            model_name="consumerinterfaceproduct",
            name="description_en",
            field=models.CharField(
                blank=True, default="", max_length=500, null=True
            ),
        ),
        migrations.AddField(
            model_name="consumerinterfaceproduct",
            name="description_es",
            field=models.CharField(
                blank=True, default="", max_length=500, null=True
            ),
        ),
        migrations.AddField(
            model_name="consumerinterfaceproduct",
            name="description_fr",
            field=models.CharField(
                blank=True, default="", max_length=500, null=True
            ),
        ),
        migrations.AddField(
            model_name="consumerinterfaceproduct",
            name="description_nl",
            field=models.CharField(
                blank=True, default="", max_length=500, null=True
            ),
        ),
        migrations.AddField(
            model_name="consumerinterfacestage",
            name="actor_name_en",
            field=models.CharField(
                blank=True, default="", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="consumerinterfacestage",
            name="actor_name_es",
            field=models.CharField(
                blank=True, default="", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="consumerinterfacestage",
            name="actor_name_fr",
            field=models.CharField(
                blank=True, default="", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="consumerinterfacestage",
            name="actor_name_nl",
            field=models.CharField(
                blank=True, default="", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="consumerinterfacestage",
            name="description_en",
            field=models.CharField(
                blank=True, default="", max_length=500, null=True
            ),
        ),
        migrations.AddField(
            model_name="consumerinterfacestage",
            name="description_es",
            field=models.CharField(
                blank=True, default="", max_length=500, null=True
            ),
        ),
        migrations.AddField(
            model_name="consumerinterfacestage",
            name="description_fr",
            field=models.CharField(
                blank=True, default="", max_length=500, null=True
            ),
        ),
        migrations.AddField(
            model_name="consumerinterfacestage",
            name="description_nl",
            field=models.CharField(
                blank=True, default="", max_length=500, null=True
            ),
        ),
    ]
