# Generated by Django 2.2.6 on 2022-08-26 09:42

import common.library
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0009_auto_20220614_1013'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0009_auto_20220603_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_storyproject_objects', to=settings.AUTH_USER_MODEL)),
                ('updater', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater_storyproject_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='citheme',
            name='default_claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_claim_themes', to='claims.Claim'),
        ),
        migrations.AddField(
            model_name='citheme',
            name='mobile_banner_image',
            field=models.FileField(blank=True, upload_to=common.library._get_file_path),
        ),
        migrations.AddField(
            model_name='citheme',
            name='show_action_button',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='citheme',
            name='show_share_button',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='citheme',
            name='version',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.CreateModel(
            name='StoryProjectStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=250)),
                ('value', models.DecimalField(decimal_places=3, default=0, max_digits=25)),
                ('is_visible', models.BooleanField(default=True)),
                ('creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_storyprojectstats_objects', to=settings.AUTH_USER_MODEL)),
                ('story_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_project_stats', to='dashboard.StoryProject')),
                ('updater', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater_storyprojectstats_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='citheme',
            name='story_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='story_project_themes', to='dashboard.StoryProject'),
        ),
    ]
