# Generated by Django 2.2.6 on 2022-08-29 03:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0010_auto_20220826_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_program_objects', to=settings.AUTH_USER_MODEL)),
                ('updater', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater_program_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProgramStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=250)),
                ('value', models.DecimalField(decimal_places=3, default=0, max_digits=25)),
                ('is_visible', models.BooleanField(default=True)),
                ('creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_programstat_objects', to=settings.AUTH_USER_MODEL)),
                ('story_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_stats', to='dashboard.Program')),
                ('updater', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater_programstat_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='storyprojectstats',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='storyprojectstats',
            name='story_project',
        ),
        migrations.RemoveField(
            model_name='storyprojectstats',
            name='updater',
        ),
        migrations.RemoveField(
            model_name='citheme',
            name='story_project',
        ),
        migrations.DeleteModel(
            name='StoryProject',
        ),
        migrations.DeleteModel(
            name='StoryProjectStats',
        ),
        migrations.AddField(
            model_name='citheme',
            name='story_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_themes', to='dashboard.Program'),
        ),
    ]
