# Generated by Django 2.2.6 on 2022-08-29 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20220829_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='description_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='description_nl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='title_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='title_es',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='title_fr',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='title_nl',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='programstat',
            name='name_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='programstat',
            name='name_es',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='programstat',
            name='name_fr',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='programstat',
            name='name_nl',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
