# Generated by Django 2.2.6 on 2022-09-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20220829_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='citheme',
            name='primary_colour_shade_1',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='citheme',
            name='primary_colour_shade_2',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='citheme',
            name='stroke_colour',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
