# Generated by Django 2.2.6 on 2023-03-16 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_citheme_page_bg_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='citheme',
            name='default_languages',
            field=models.CharField(blank=True, default='en', max_length=500, null=True),
        ),
    ]
