# Generated by Django 2.2.6 on 2023-03-16 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_citheme_default_languages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citheme',
            old_name='default_languages',
            new_name='default_language',
        ),
    ]
