# Generated by Django 2.2.6 on 2023-06-21 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_auto_20230619_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumerinterfaceproduct',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='consumerinterfaceproduct',
            name='name_es',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='consumerinterfaceproduct',
            name='name_fr',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='consumerinterfaceproduct',
            name='name_nl',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
