# Generated by Django 2.2.6 on 2023-06-21 17:17

import common.library
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chains', '0038_auto_20230621_2247'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0022_auto_20230621_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumerInterfaceActor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('name_en', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('name_es', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('name_fr', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('name_nl', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('image', models.FileField(blank=True, upload_to=common.library._get_file_path)),
                ('description', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('description_en', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('description_es', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('description_fr', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('description_nl', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply_chains.Node')),
                ('creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_consumerinterfaceactor_objects', to=settings.AUTH_USER_MODEL)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actors', to='dashboard.CITheme')),
                ('updater', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater_consumerinterfaceactor_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
    ]
