# Generated by Django 2.2.6 on 2023-09-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_auto_20230913_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumerinterfaceclaimintervention',
            name='external_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
