# Generated by Django 2.2.6 on 2023-09-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_consumerinterfaceclaimintervention_external_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='citheme',
            name='primary_colour_shade_3',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
