# Generated by Django 2.2.6 on 2023-09-27 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_citheme_primary_colour_shade_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='citheme',
            name='primary_colour_shade_4',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='citheme',
            name='primary_colour_shade_5',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
