# Generated by Django 2.2.6 on 2023-10-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_auto_20230927_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='citheme',
            name='video_url_en',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='citheme',
            name='video_url_es',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='citheme',
            name='video_url_fr',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='citheme',
            name='video_url_nl',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
