# Generated by Django 2.2.6 on 2024-05-24 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_auto_20231012_1725'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citheme',
            options={'ordering': ('id',)},
        ),
    ]
