# Constants for Transparency request app
# Transparency request type choices
TRANSPARENCY_REQUEST_TYPE_TRANSACTION = 1
TRANSPARENCY_REQUEST_TYPE_CLAIM = 2
TRANSPARENCY_REQUEST_TYPE_INFORMATION = 3
TRANSPARENCY_REQUEST_TYPE_CONNECTION = 4

TRANSPARENCY_REQUEST_TYPE_CHOICES = (
    (TRANSPARENCY_REQUEST_TYPE_TRANSACTION, "Transaction"),
    (TRANSPARENCY_REQUEST_TYPE_CLAIM, "Claim"),
    (TRANSPARENCY_REQUEST_TYPE_INFORMATION, "Information"),
    (TRANSPARENCY_REQUEST_TYPE_CONNECTION, "Connection"),
)

# Transparency request direction choices
TRANSPARENCY_REQUEST_DIRECTION_INCOMING = 1
TRANSPARENCY_REQUEST_DIRECTION_OUTGOING = 2

TRANSPARENCY_REQUEST_DIRECTION_CHOICES = (
    (TRANSPARENCY_REQUEST_DIRECTION_INCOMING, "Incoming"),
    (TRANSPARENCY_REQUEST_DIRECTION_OUTGOING, "Outgoing"),
)

# Transparency request status choices

TRANSPARENCY_REQUEST_STATUS_PENDING = 1
TRANSPARENCY_REQUEST_STATUS_COMPLETED = 2
TRANSPARENCY_REQUEST_STATUS_DECLINED = 3
TRANSPARENCY_REQUEST_STATUS_ACKNOWLEDGED = 4

TRANSPARENCY_REQUEST_STATUS_CHOICES = (
    (TRANSPARENCY_REQUEST_STATUS_PENDING, "Pending"),
    (TRANSPARENCY_REQUEST_STATUS_COMPLETED, "Completed"),
    (TRANSPARENCY_REQUEST_STATUS_DECLINED, "Declined"),
    (TRANSPARENCY_REQUEST_STATUS_ACKNOWLEDGED, "Acknowledged"),
)
