"""Constants used in the app communications."""
# Notification Actions

NOTIF_ACTION_NORMAL = 1
NOTIF_ACTION_EMAIL = 2
NOTIF_ACTION_PUSH = 3
NOTIF_ACTION_PUSH_N_EMAIL = 4
NOTIF_ACTION_PUSH_EMAIL_N_SMS = 5
NOTIF_ACTION_EMAIL_N_SMS = 6

NOTIF_ACTION_CHOICES = (
    (NOTIF_ACTION_NORMAL, "Normal"),
    (NOTIF_ACTION_EMAIL, "Email"),
    (NOTIF_ACTION_PUSH, "Push notification"),
    (NOTIF_ACTION_PUSH_N_EMAIL, "Push and email"),
    (NOTIF_ACTION_PUSH_EMAIL_N_SMS, "Push, email and SMS"),
    (NOTIF_ACTION_EMAIL_N_SMS, "Email and SMS"),
)

# Notification Type

NOTIF_TYPE_VERIFY_EMAIL = 5
NOTIF_TYPE_RESET_PASSWORD = 7
NOTIF_TYPE_MAGIC_LOGIN = 8
NOTIF_TYPE_MEMBER_INVITE = 9
NOTIF_TYPE_CHANGE_EMAIL = 11
NOTIF_TYPE_NEW_NODE_INVITE = 10
NOTIF_TYPE_EXISTING_NODE_INVITE = 12
NOTIF_TYPE_RECEIVE_STOCK = 13
NOTIF_TYPE_SENT_STOCK = 14
NOTIF_TYPE_TRANSACTION_REJECTED = 15
NOTIF_TYPE_RECEIVE_STOCK_REQUEST = 16
NOTIF_TYPE_DECLINE_STOCK_REQUEST = 17
NOTIF_TYPE_RECEIVE_CLAIM_REQUEST = 22
NOTIF_TYPE_DECLINE_CLAIM_REQUEST = 23
NOTIF_TYPE_RECEIVE_INFORMATION_REQUEST = 24
NOTIF_TYPE_DECLINE_INFORMATION_REQUEST = 25
NOTIF_TYPE_RECEIVE_CONNECTION_REQUEST = 26
NOTIF_TYPE_DECLINE_CONNECTION_REQUEST = 27
NOTIF_TYPE_INFORMATION_RESPONSE = 28
NOTIF_TYPE_CLAIM_RESPONSE = 29
NOTIF_TYPE_RECEIVE_VERIFICATION_REQUEST = 18
NOTIF_TYPE_APPROVED_CLAIM = 19
NOTIF_TYPE_REJECTED_CLAIM = 20
NOTIF_TYPE_CLAIM_COMMENT = 21
NOTIF_TYPE_WEEK_ONE_REMINDER = 30
NOTIF_TYPE_WEEK_TWO_REMINDER = 31
NOTIF_TYPE_FFADMIN_NEW_NODE_INVITE = 32
NOTIF_TYPE_FFADMIN_EXISTING_NODE_INVITE = 33
NOTIF_TYPE_MAGIC_LOGIN_ADMIN = 34
NOTIF_TYPE_EMAIL_LOGIN = 35
# Max Value = 33

NOTIF_TYPE_CHOICES = (
    (NOTIF_TYPE_VERIFY_EMAIL, "Verify email"),
    (NOTIF_TYPE_RESET_PASSWORD, "Reset password email"),
    (NOTIF_TYPE_MAGIC_LOGIN, "Magic login email"),
    (NOTIF_TYPE_MAGIC_LOGIN_ADMIN, "Admin magic login email"),
    (NOTIF_TYPE_MEMBER_INVITE, "Invited as member"),
    (NOTIF_TYPE_NEW_NODE_INVITE, "Node Invite"),
    (NOTIF_TYPE_FFADMIN_NEW_NODE_INVITE, "FFAdmin Invite"),
    (NOTIF_TYPE_FFADMIN_EXISTING_NODE_INVITE, "FFAdmin Existing Node Invite"),
    (NOTIF_TYPE_CHANGE_EMAIL, "Email Change"),
    (NOTIF_TYPE_EXISTING_NODE_INVITE, "Existing Node Invite"),
    (NOTIF_TYPE_WEEK_ONE_REMINDER, "Week One Reminder"),
    (NOTIF_TYPE_WEEK_TWO_REMINDER, "Week Two Reminder"),
    (NOTIF_TYPE_RECEIVE_STOCK, "Received stock"),
    (NOTIF_TYPE_SENT_STOCK, "Sent stock"),
    (NOTIF_TYPE_TRANSACTION_REJECTED, "Transaction Rejected"),
    (NOTIF_TYPE_RECEIVE_STOCK_REQUEST, "Received Stock Request"),
    (NOTIF_TYPE_DECLINE_STOCK_REQUEST, "Decline Stock Request"),
    (NOTIF_TYPE_RECEIVE_CLAIM_REQUEST, "Received Claim Request"),
    (NOTIF_TYPE_DECLINE_CLAIM_REQUEST, "Decline Claim Request"),
    (NOTIF_TYPE_RECEIVE_INFORMATION_REQUEST, "Received Information Request"),
    (NOTIF_TYPE_DECLINE_INFORMATION_REQUEST, "Decline Information Request"),
    (NOTIF_TYPE_RECEIVE_CONNECTION_REQUEST, "Received Connection Request"),
    (NOTIF_TYPE_RECEIVE_VERIFICATION_REQUEST, "Received verification Request"),
    (NOTIF_TYPE_APPROVED_CLAIM, "Approved claim"),
    (NOTIF_TYPE_REJECTED_CLAIM, "Rejected claim"),
    (NOTIF_TYPE_CLAIM_COMMENT, "Added comment"),
    (NOTIF_TYPE_DECLINE_CONNECTION_REQUEST, "Decline Connection Request"),
    (NOTIF_TYPE_INFORMATION_RESPONSE, "Received Information Response"),
    (NOTIF_TYPE_CLAIM_RESPONSE, "Received Claim Response"),
)
