# Generated by Django 2.2.6 on 2021-03-14 18:05
import common.library
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("number", models.IntegerField(default=0)),
                ("name", models.CharField(default="", max_length=800)),
                ("initial_quantity", models.FloatField(default=0.0)),
                ("current_quantity", models.FloatField(default=0.0)),
                (
                    "unit",
                    models.IntegerField(
                        choices=[(1, "KG"), (2, "Tonne")], default=1
                    ),
                ),
                ("verified_percentage", models.FloatField(default=0.0)),
                (
                    "type",
                    models.IntegerField(
                        choices=[(1, "Solid"), (2, "Intermediate")], default=1
                    ),
                ),
                (
                    "source_type",
                    models.IntegerField(
                        choices=[
                            (1, "Received"),
                            (2, "Returned"),
                            (3, "Processed"),
                            (4, "Merged"),
                        ],
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, default="", max_length=1000),
                ),
                (
                    "blockchain_public",
                    models.CharField(
                        blank=True, default="", max_length=200, null=True
                    ),
                ),
            ],
            options={
                "ordering": ("-created_on",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=1000),
                ),
                (
                    "image",
                    models.FileField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to=common.library._get_file_path,
                    ),
                ),
                (
                    "image_name",
                    models.CharField(blank=True, default="", max_length=1000),
                ),
                (
                    "type",
                    models.IntegerField(
                        choices=[(1, "Global"), (2, "Local")], default=1
                    ),
                ),
                ("deleted", models.BooleanField(default=False)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="creator_product_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_on",),
                "abstract": False,
            },
        ),
    ]
