# Generated by Django 2.2.6 on 2021-03-14 18:05
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0001_initial"),
        ("blockchain", "0001_initial"),
        ("transactions", "0001_initial"),
        ("supply_chains", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="owners",
            field=models.ManyToManyField(blank=True, to="supply_chains.Node"),
        ),
        migrations.AddField(
            model_name="product",
            name="supply_chain",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="supply_chains.SupplyChain",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="updater",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updater_product_objects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="batch",
            name="block_chain_request",
            field=models.OneToOneField(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products_batch",
                to="blockchain.BlockchainRequest",
            ),
        ),
        migrations.AddField(
            model_name="batch",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="creator_batch_objects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="batch",
            name="node",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="batches",
                to="supply_chains.Node",
            ),
        ),
        migrations.AddField(
            model_name="batch",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="batches",
                to="products.Product",
            ),
        ),
        migrations.AddField(
            model_name="batch",
            name="source_transaction",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="result_batches",
                to="transactions.Transaction",
            ),
        ),
        migrations.AddField(
            model_name="batch",
            name="updater",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updater_batch_objects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
