# Generated by Django 2.2.6 on 2021-03-14 20:53
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        (
            "blockchain",
            "0002_associatetokenrequest_callbackresponse_"
            "createtokenrequest_kyctokenrequest_submitmessagerequest_trans",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("supply_chains", "0004_auto_20210315_0223"),
        ("products", "0002_auto_20210314_2335"),
    ]

    operations = [
        migrations.RenameField(
            model_name="batch",
            old_name="blockchain_public",
            new_name="blockchain_id",
        ),
        migrations.AddField(
            model_name="batch",
            name="blockchain_hash",
            field=models.CharField(
                blank=True, default="", max_length=2000, null=True
            ),
        ),
        migrations.AddField(
            model_name="batch",
            name="node_wallet",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="batches",
                to="supply_chains.BlockchainWallet",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="block_chain_request",
            field=models.OneToOneField(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products_product",
                to="blockchain.BlockchainRequest",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="token_id",
            field=models.CharField(
                blank=True, default="", max_length=50, null=True
            ),
        ),
        migrations.CreateModel(
            name="NodeProduct",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("associated", models.BooleanField(default=False)),
                (
                    "association_hash",
                    models.CharField(
                        blank=True, default="", max_length=200, null=True
                    ),
                ),
                ("kyc_completed", models.BooleanField(default=False)),
                (
                    "kyc_hash",
                    models.CharField(
                        blank=True, default="", max_length=200, null=True
                    ),
                ),
                (
                    "association",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="associated_products",
                        to="supply_chains.WalletTokenAssociation",
                    ),
                ),
                (
                    "block_chain_request",
                    models.OneToOneField(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products_nodeproduct",
                        to="blockchain.BlockchainRequest",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="creator_nodeproduct_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "node_wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="node_products",
                        to="supply_chains.BlockchainWallet",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nodes",
                        to="products.Product",
                    ),
                ),
                (
                    "updater",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updater_nodeproduct_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_on",),
                "abstract": False,
            },
        ),
    ]
