# Generated by Django 2.2.6 on 2021-04-05 11:51
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_auto_20210316_1834"),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="old_blockchain_hash",
            field=models.CharField(
                blank=True, default="", max_length=2000, null=True
            ),
        ),
    ]
