# Generated by Django 2.2.6 on 2021-04-05 17:52
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_auto_20210405_1822"),
    ]

    operations = [
        migrations.RenameField(
            model_name="batch",
            old_name="old_blockchain_hash",
            new_name="topl_blockchain_hash",
        ),
    ]
