# Generated by Django 2.2.6 on 2023-03-07 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supply_chains', '0028_farmer_extra_fields'),
        ('products', '0012_auto_20220705_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchFarmerMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_farmers', to='products.Batch')),
                ('creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_batchfarmermapping_objects', to=settings.AUTH_USER_MODEL)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_batches', to='supply_chains.Farmer')),
                ('updater', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater_batchfarmermapping_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('batch', 'farmer')},
            },
        ),
    ]
