# Generated by Django 2.2.6 on 2023-06-09 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_batchfarmermapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='external_source',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
