# Generated by Django 2.2.6 on 2023-11-15 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_batch_external_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='external_lat',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='external_long',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
