# Generated by Django 2.2.6 on 2024-02-14 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_product_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_batches', to='products.Batch'),
        ),
    ]
