# Generated by Django 2.2.6 on 2024-02-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_batch_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='parent',
        ),
        migrations.AddField(
            model_name='batch',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='child_batches', to='products.Batch'),
        ),
    ]
