# Generated by Django 2.2.6 on 2024-03-21 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20240229_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
