# Generated by Django 2.2.6 on 2024-06-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_batch_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='navigate_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
