# Generated by Django 2.2.6 on 2025-04-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_batch_gtin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='unit',
            field=models.IntegerField(choices=[(1, 'KG'), (2, 'Tonne'), (3, 'Metric Ton of CO2e')], default=1),
        ),
        migrations.AlterField(
            model_name='batchmigration',
            name='unit',
            field=models.IntegerField(choices=[(1, 'KG'), (2, 'Tonne'), (3, 'Metric Ton of CO2e')], default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.IntegerField(choices=[(1, 'Global'), (2, 'Local'), (3, 'Carbon')], default=1),
        ),
    ]
