# Generated by Django 2.2.6 on 2021-03-14 18:05
import common.library
import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blockchain", "0001_initial"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockchainWallet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "public_key",
                    models.CharField(
                        blank=True, default="", max_length=200, null=True
                    ),
                ),
                (
                    "secret",
                    models.CharField(
                        blank=True, default="", max_length=200, null=True
                    ),
                ),
                (
                    "block_chain_request",
                    models.OneToOneField(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supply_chains_blockchainaccount",
                        to="blockchain.BlockchainRequest",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="creator_blockchainaccount_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updater",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updater_blockchainaccount_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_on",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Connection",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "graph_uid",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "Claimed"),
                            (2, "Identified"),
                            (3, "Verified"),
                            (4, "Rejected"),
                        ],
                        default=1,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("-created_on",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Node",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "house_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "street",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "city",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "sub_province",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "province",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "country",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("latitude", models.FloatField(default=0.0)),
                ("longitude", models.FloatField(default=0.0)),
                (
                    "zipcode",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "graph_uid",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (1, "Company"),
                            (2, "Farmer"),
                            (3, "Verifier"),
                        ]
                    ),
                ),
                (
                    "profile_mode",
                    models.IntegerField(
                        choices=[(1, "Network"), (2, "Transaction")], default=1
                    ),
                ),
                (
                    "identification_no",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("registration_date", models.DateField(blank=True, null=True)),
                (
                    "email",
                    models.EmailField(blank=True, max_length=100, null=True),
                ),
                (
                    "phone",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "description_basic",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "description_full",
                    models.CharField(blank=True, default="", max_length=2000),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to=common.library._get_file_path,
                    ),
                ),
                (
                    "disclosure_level",
                    models.IntegerField(
                        choices=[(1, "Custom"), (2, "Full")], default=1
                    ),
                ),
                (
                    "visible_fields",
                    models.CharField(default="{}", max_length=1000),
                ),
                (
                    "date_invited",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("date_joined", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "Active"), (2, "Inactive"), (3, "Block")],
                        default=2,
                    ),
                ),
                ("verified", models.BooleanField(default=False)),
                (
                    "blockchain_address",
                    models.CharField(
                        blank=True, default="", max_length=200, null=True
                    ),
                ),
                (
                    "selected_theme",
                    models.IntegerField(
                        choices=[(1, "Default"), (2, "Custom")], default=1
                    ),
                ),
                (
                    "plan",
                    models.IntegerField(
                        choices=[(1, "Basic"), (2, "Premium")], default=1
                    ),
                ),
                (
                    "blockchain_account",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="supply_chains.BlockchainWallet",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="creator_node_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="SupplyChain",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=1000),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to=common.library._get_file_path,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="creator_supplychain_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updater",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updater_supplychain_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Farmer",
            fields=[
                (
                    "node_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="supply_chains.Node",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                (
                    "last_name",
                    models.CharField(
                        blank=True, default="", max_length=100, null=True
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True, default="", max_length=50, null=True
                    ),
                ),
                ("dob", models.DateField(blank=True, null=True)),
                (
                    "birth_city",
                    models.CharField(
                        blank=True, default="", max_length=500, null=True
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        blank=True, default="", max_length=50, null=True
                    ),
                ),
                (
                    "family_members",
                    models.IntegerField(blank=True, default=1, null=True),
                ),
                (
                    "farm_area",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("income_from_main_product", models.FloatField(default=0.0)),
                (
                    "income_from_other_sources",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "main_product",
                    models.CharField(
                        blank=True, default="", max_length=100, null=True
                    ),
                ),
            ],
            options={
                "ordering": ("-created_on",),
                "abstract": False,
            },
            bases=("supply_chains.node", models.Model),
        ),
        migrations.CreateModel(
            name="Verifier",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="creator_verifier_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verifier_sc_objects",
                        to="supply_chains.Node",
                    ),
                ),
                (
                    "supply_chain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sc_verifier_objects",
                        to="supply_chains.SupplyChain",
                    ),
                ),
                (
                    "updater",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updater_verifier_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_on",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Operation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "node_type",
                    models.IntegerField(
                        choices=[
                            (1, "Company"),
                            (2, "Farmer"),
                            (3, "Verifier"),
                        ]
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "image",
                    models.FileField(
                        blank=True, upload_to=common.library._get_file_path
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="creator_operation_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updater",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updater_operation_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_on",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="NodeSupplyChain",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("traceable", models.BooleanField(default=False)),
                ("complexity", models.FloatField(default=0)),
                ("tier_count", models.IntegerField(default=0)),
                ("chain_length", models.FloatField(default=0.0)),
                ("actor_count", models.IntegerField(default=0)),
                ("supplier_count", models.IntegerField(default=0)),
                ("farmer_count", models.IntegerField(default=0)),
                ("invited_actor_count", models.IntegerField(default=0)),
                ("mapped_actor_count", models.IntegerField(default=0)),
                ("active_actor_count", models.IntegerField(default=0)),
                ("pending_invite_count", models.IntegerField(default=0)),
                (
                    "operation_stats",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, default=dict, null=True
                    ),
                ),
                (
                    "farmer_coorinates",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, default=dict, null=True
                    ),
                ),
                (
                    "supplier_coorinates",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, default=dict, null=True
                    ),
                ),
                (
                    "buyer_ids",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, default=list, null=True
                    ),
                ),
                (
                    "supplier_ids",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, default=list, null=True
                    ),
                ),
                (
                    "farmer_ids",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, default=list, null=True
                    ),
                ),
                (
                    "invited_by",
                    models.IntegerField(
                        choices=[
                            (1, "Company Invited"),
                            (2, "FFAdmin Invited"),
                            (3, "Signed Up"),
                        ],
                        default=1,
                    ),
                ),
                ("active", models.BooleanField(default=False)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="creator_nodesupplychain_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="supply_chains.Node",
                    ),
                ),
                (
                    "supply_chain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="supply_chains.SupplyChain",
                    ),
                ),
                (
                    "updater",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updater_nodesupplychain_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_on",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="NodeMember",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "type",
                    models.IntegerField(
                        choices=[(1, "Admin"), (2, "Member"), (3, "Viewer")],
                        default=2,
                    ),
                ),
                ("active", models.BooleanField(default=False)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="creator_nodemember_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nodemembers",
                        to="supply_chains.Node",
                    ),
                ),
                (
                    "updater",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updater_nodemember_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usernodes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vtoken",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.ValidationToken",
                    ),
                ),
            ],
            options={
                "unique_together": {("node", "user")},
            },
        ),
        migrations.CreateModel(
            name="NodeManager",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="creator_nodemanager_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="managed_node_objects",
                        to="supply_chains.Node",
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="node_manager_objects",
                        to="supply_chains.Node",
                    ),
                ),
                (
                    "updater",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updater_nodemanager_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_on",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="NodeFeatures",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("dashboard_theming", models.BooleanField(default=False)),
                (
                    "consumer_interface_theming",
                    models.BooleanField(default=False),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="creator_nodefeatures_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "node",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="supply_chains.Node",
                    ),
                ),
                (
                    "updater",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updater_nodefeatures_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_on",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="NodeDocument",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "name",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to=common.library._get_file_path,
                    ),
                ),
                (
                    "type",
                    models.IntegerField(choices=[(1, "Default")], default=1),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="creator_nodedocument_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="supply_chains.Node",
                    ),
                ),
                (
                    "updater",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updater_nodedocument_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_on",),
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="node",
            name="managers",
            field=models.ManyToManyField(
                related_name="nodes_managed",
                through="supply_chains.NodeManager",
                to="supply_chains.Node",
            ),
        ),
        migrations.AddField(
            model_name="node",
            name="members",
            field=models.ManyToManyField(
                related_name="nodes",
                through="supply_chains.NodeMember",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="node",
            name="other_operations",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                related_name="secondary_nodes",
                to="supply_chains.Operation",
            ),
        ),
        migrations.AddField(
            model_name="node",
            name="primary_operation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_nodes",
                to="supply_chains.Operation",
            ),
        ),
        migrations.AddField(
            model_name="node",
            name="products",
            field=models.ManyToManyField(
                related_name="actors",
                through="products.Batch",
                to="products.Product",
            ),
        ),
        migrations.AddField(
            model_name="node",
            name="suppliers",
            field=models.ManyToManyField(
                related_name="buyers",
                through="supply_chains.Connection",
                to="supply_chains.Node",
            ),
        ),
        migrations.AddField(
            model_name="node",
            name="supply_chains",
            field=models.ManyToManyField(
                related_name="nodes",
                through="supply_chains.NodeSupplyChain",
                to="supply_chains.SupplyChain",
            ),
        ),
        migrations.AddField(
            model_name="node",
            name="updater",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updater_node_objects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="node",
            name="verifier_supply_chains",
            field=models.ManyToManyField(
                related_name="verifiers",
                through="supply_chains.Verifier",
                to="supply_chains.SupplyChain",
            ),
        ),
        migrations.CreateModel(
            name="Label",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=50)),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="labels_created",
                        to="supply_chains.Node",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="creator_label_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supply_chains",
                    models.ManyToManyField(
                        blank=True,
                        related_name="labels",
                        to="supply_chains.SupplyChain",
                    ),
                ),
                (
                    "updater",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updater_label_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_on",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "relation",
                    models.IntegerField(
                        choices=[(1, "Supplier"), (2, "Buyer")], default=1
                    ),
                ),
                (
                    "message",
                    models.TextField(blank=True, default="", null=True),
                ),
                ("email_sent", models.BooleanField(default=False)),
                (
                    "invited_on",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "type",
                    models.IntegerField(
                        choices=[(1, "Direct"), (2, "Indirect")], default=1
                    ),
                ),
                (
                    "connection",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitation",
                        to="supply_chains.Connection",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="creator_invitation_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "incharge",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.Person",
                    ),
                ),
                (
                    "invitee",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invitations_received",
                        to="supply_chains.Node",
                    ),
                ),
                (
                    "inviter",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invitations_sent",
                        to="supply_chains.Node",
                    ),
                ),
                (
                    "tokens",
                    models.ManyToManyField(
                        blank=True,
                        related_name="invitations",
                        to="accounts.ValidationToken",
                    ),
                ),
                (
                    "updater",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updater_invitation_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_on",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ConnectionLabel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="supply_chains.Connection",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="creator_connectionlabel_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "label",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="supply_chains.Label",
                    ),
                ),
                (
                    "updater",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updater_connectionlabel_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_on",),
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="connection",
            name="buyer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supplier_connections",
                to="supply_chains.Node",
            ),
        ),
        migrations.AddField(
            model_name="connection",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="creator_connection_objects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="connection",
            name="labels",
            field=models.ManyToManyField(
                related_name="connections",
                through="supply_chains.ConnectionLabel",
                to="supply_chains.Label",
            ),
        ),
        migrations.AddField(
            model_name="connection",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buyer_connections",
                to="supply_chains.Node",
            ),
        ),
        migrations.AddField(
            model_name="connection",
            name="supply_chain",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supply_chain_connections",
                to="supply_chains.SupplyChain",
            ),
        ),
        migrations.AddField(
            model_name="connection",
            name="updater",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updater_connection_objects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="AdminInvitation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="creator_admininvitation_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invitee",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_invitations_received",
                        to="supply_chains.Node",
                    ),
                ),
                (
                    "node_supply_chains",
                    models.ManyToManyField(
                        blank=True,
                        related_name="admin_invitations",
                        to="supply_chains.NodeSupplyChain",
                    ),
                ),
                (
                    "tokens",
                    models.ManyToManyField(
                        blank=True,
                        related_name="admin_invitations",
                        to="accounts.ValidationToken",
                    ),
                ),
                (
                    "updater",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updater_admininvitation_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_on",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ConnectionTag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "buyer_id",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "supplier_id",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "buyer_connection",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_tags",
                        to="supply_chains.Connection",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="creator_connectiontag_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supplier_connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buyer_tags",
                        to="supply_chains.Connection",
                    ),
                ),
                (
                    "updater",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updater_connectiontag_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("buyer_connection", "supplier_connection")
                },
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "node_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="supply_chains.Node",
                    ),
                ),
                (
                    "role",
                    models.IntegerField(
                        choices=[
                            (1, "Actor"),
                            (2, "Verifier"),
                            (3, "Actor & Verifier"),
                        ],
                        default=1,
                    ),
                ),
                ("name", models.CharField(max_length=500, unique=True)),
                (
                    "incharge",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.Person",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_on",),
                "abstract": False,
            },
            bases=("supply_chains.node",),
        ),
    ]
