# Generated by Django 2.2.6 on 2021-03-14 20:41
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("supply_chains", "0001_initial"),
    ]

    operations = [
        # migrations.RenameModel("BlockchainAccount", "BlockchainWallet")
    ]
