# Generated by Django 2.2.6 on 2021-03-14 20:53
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("supply_chains", "0002_auto_20210315_0219"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blockchainwallet",
            old_name="public_key",
            new_name="public",
        ),
        migrations.RenameField(
            model_name="blockchainwallet",
            old_name="secret",
            new_name="private",
        ),
    ]
