# Generated by Django 2.2.6 on 2021-03-14 20:53
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        (
            "blockchain",
            "0002_associatetokenrequest_callbackresponse_createtokenrequest_kyctokenrequest_submitmessagerequest_trans",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("supply_chains", "0003_auto_20210315_0223"),
    ]

    operations = [
        migrations.AddField(
            model_name="blockchainwallet",
            name="account_id",
            field=models.CharField(
                blank=True, default="", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="blockchainwallet",
            name="default",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="blockchainwallet",
            name="node",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wallets",
                to="supply_chains.Node",
            ),
        ),
        migrations.AddField(
            model_name="blockchainwallet",
            name="wallet_type",
            field=models.IntegerField(
                choices=[(101, "TOPL"), (201, "Hedera")], default=201
            ),
        ),
        migrations.AlterField(
            model_name="blockchainwallet",
            name="block_chain_request",
            field=models.OneToOneField(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supply_chains_blockchainwallet",
                to="blockchain.BlockchainRequest",
            ),
        ),
        migrations.AlterField(
            model_name="blockchainwallet",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="creator_blockchainwallet_objects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="blockchainwallet",
            name="private",
            field=models.CharField(
                blank=True, default="", max_length=2000, null=True
            ),
        ),
        migrations.AlterField(
            model_name="blockchainwallet",
            name="public",
            field=models.CharField(
                blank=True, default="", max_length=2000, null=True
            ),
        ),
        migrations.AlterField(
            model_name="blockchainwallet",
            name="updater",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updater_blockchainwallet_objects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="node",
            name="blockchain_account",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="old_node",
                to="supply_chains.BlockchainWallet",
            ),
        ),
        migrations.CreateModel(
            name="WalletTopUp",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("amount", models.FloatField(default=0)),
                (
                    "blockchain_id",
                    models.CharField(default="", max_length=500),
                ),
                (
                    "blockchain_address",
                    models.CharField(default="", max_length=500),
                ),
                (
                    "block_chain_request",
                    models.OneToOneField(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supply_chains_wallettopup",
                        to="blockchain.BlockchainRequest",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="creator_wallettopup_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "node_wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="supply_chains.BlockchainWallet",
                    ),
                ),
                (
                    "updater",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updater_wallettopup_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_on",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WalletTokenAssociation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("success", models.BooleanField(default=False)),
                (
                    "block_chain_request",
                    models.OneToOneField(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supply_chains_wallettokenassociation",
                        to="blockchain.BlockchainRequest",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="creator_wallettokenassociation_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "node_wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="associations",
                        to="supply_chains.BlockchainWallet",
                    ),
                ),
                (
                    "supply_chain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="associations",
                        to="supply_chains.SupplyChain",
                    ),
                ),
                (
                    "updater",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updater_wallettokenassociation_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_on",),
                "abstract": False,
            },
        ),
    ]
