# Generated by Django 2.2.6 on 2021-04-06 07:24
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("supply_chains", "0004_auto_20210315_0223"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connection",
            name="status",
            field=models.IntegerField(
                choices=[
                    (101, "Claimed"),
                    (201, "Verified"),
                    (301, "Rejected"),
                ],
                default=101,
            ),
        ),
    ]
