# Generated by Django 2.2.6 on 2021-04-06 07:30
from django.db import migrations


def change_connection_status(apps, schema_editor):
    """Change database values of existing connections to be in sync with the
    constant values."""
    try:
        Connection = apps.get_model("supply_chains", "Connection")
        Connection.objects.filter(status=1).update(status=101)
        Connection.objects.filter(status=2).update(status=101)
        Connection.objects.filter(status=3).update(status=201)
        Connection.objects.filter(status=4).update(status=301)
    except Exception:
        pass


class Migration(migrations.Migration):
    dependencies = [
        ("supply_chains", "0005_auto_20210406_1254"),
    ]

    operations = [migrations.RunPython(change_connection_status)]
