# Generated by Django 2.2.6 on 2021-04-19 20:05
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("supply_chains", "0006_auto_20210406_1300"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallettopup",
            name="node_wallet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recharges",
                to="supply_chains.BlockchainWallet",
            ),
        ),
    ]
