# Generated by Django 2.2.6 on 2021-04-29 06:21
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("blockchain", "0011_auto_20210426_2211"),
        ("supply_chains", "0012_auto_20210429_0127"),
    ]

    operations = [
        migrations.AddField(
            model_name="blockchainwallet",
            name="deferred_requests",
            field=models.ManyToManyField(
                blank=True,
                related_name="initiator_wallet",
                to="blockchain.BlockchainRequest",
            ),
        ),
    ]
