# Generated by Django 2.2.6 on 2021-04-30 09:56
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("supply_chains", "0013_blockchainwallet_deferred_requests"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallettokenassociation",
            name="association_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
