# Generated by Django 2.2.6 on 2021-06-21 10:48
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("supply_chains", "0014_wallettokenassociation_association_confirmed"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationSupplyChain",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="creator_operationsupplychain_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supply_chain_objects",
                        to="supply_chains.Operation",
                    ),
                ),
                (
                    "supply_chain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operation_objects",
                        to="supply_chains.SupplyChain",
                    ),
                ),
                (
                    "updater",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updater_operationsupplychain_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("supply_chain", "operation")},
            },
        ),
        migrations.AddField(
            model_name="operation",
            name="supply_chains",
            field=models.ManyToManyField(
                related_name="operations",
                through="supply_chains.OperationSupplyChain",
                to="supply_chains.SupplyChain",
            ),
        ),
    ]
