# Generated by Django 2.2.6 on 2021-07-12 10:43
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("supply_chains", "0015_auto_20210621_1618"),
    ]

    operations = [
        migrations.AddField(
            model_name="nodesupplychain",
            name="other_operations",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                related_name="secondary_node_supplychain",
                to="supply_chains.Operation",
            ),
        ),
        migrations.AddField(
            model_name="nodesupplychain",
            name="primary_operation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_node_supplychain",
                to="supply_chains.Operation",
            ),
        ),
    ]
