# Generated by Django 2.2.6 on 2021-10-26 11:00
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("supply_chains", "0017_farmer_id_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="bulkexceluploads",
            name="file_hash",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
