# Generated by Django 2.2.6 on 2021-10-27 04:24
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("supply_chains", "0018_bulkexceluploads_file_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="bulkexceluploads",
            name="used",
            field=models.BooleanField(default=False),
        ),
    ]
