# Generated by Django 2.2.6 on 2021-11-18 09:15
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("supply_chains", "0019_bulkexceluploads_used"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farmer",
            name="farm_area",
            field=models.CharField(
                blank=True, default="", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="farmer",
            name="income_from_main_product",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name="farmer",
            name="income_from_other_sources",
            field=models.CharField(
                blank=True, default="", max_length=500, null=True
            ),
        ),
    ]
