# Generated by Django 2.2.6 on 2022-06-03 07:32
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("supply_chains", "0022_auto_20220602_1543"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="name_en",
            field=models.CharField(max_length=500, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="company",
            name="name_es",
            field=models.CharField(max_length=500, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="company",
            name="name_fr",
            field=models.CharField(max_length=500, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="company",
            name="name_nl",
            field=models.CharField(max_length=500, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="farmer",
            name="first_name_en",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="farmer",
            name="first_name_es",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="farmer",
            name="first_name_fr",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="farmer",
            name="first_name_nl",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="farmer",
            name="last_name_en",
            field=models.CharField(
                blank=True, default="", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="farmer",
            name="last_name_es",
            field=models.CharField(
                blank=True, default="", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="farmer",
            name="last_name_fr",
            field=models.CharField(
                blank=True, default="", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="farmer",
            name="last_name_nl",
            field=models.CharField(
                blank=True, default="", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="node",
            name="description_basic_en",
            field=models.CharField(
                blank=True, default="", max_length=500, null=True
            ),
        ),
        migrations.AddField(
            model_name="node",
            name="description_basic_es",
            field=models.CharField(
                blank=True, default="", max_length=500, null=True
            ),
        ),
        migrations.AddField(
            model_name="node",
            name="description_basic_fr",
            field=models.CharField(
                blank=True, default="", max_length=500, null=True
            ),
        ),
        migrations.AddField(
            model_name="node",
            name="description_basic_nl",
            field=models.CharField(
                blank=True, default="", max_length=500, null=True
            ),
        ),
    ]
