# Generated by Django 2.2.6 on 2022-06-13 12:37
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("supply_chains", "0023_auto_20220603_1302"),
        ("supply_chains", "0021_auto_20220422_1157"),
    ]

    operations = []
