# Generated by Django 2.2.6 on 2022-06-20 08:37
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("supply_chains", "0024_merge_20220613_1807"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="available_languages",
            field=models.CharField(default="en", max_length=500),
        ),
    ]
