# Generated by Django 2.2.6 on 2022-08-11 09:39

from django.db import migrations
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chains', '0026_auto_20220620_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='app_custom_fields',
            field=django_extensions.db.fields.json.JSONField(blank=True, default=dict, null=True),
        ),
    ]
