# Generated by Django 2.2.6 on 2022-09-13 10:49

from django.db import migrations
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chains', '0027_node_app_custom_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='extra_fields',
            field=django_extensions.db.fields.json.JSONField(blank=True, default=dict, null=True),
        ),
    ]
