# Generated by Django 2.2.6 on 2023-03-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chains', '0028_farmer_extra_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='buy_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='node',
            name='quality_correction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='node',
            name='sell_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='node',
            name='show_price_comparison',
            field=models.BooleanField(default=True),
        ),
    ]
