# Generated by Django 2.2.6 on 2023-04-04 07:27

import common.library
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def initialize(apps, scheme):
    reference_model = apps.get_model('supply_chains', 'Reference')
    farmer_reference_model = apps.get_model('supply_chains', 'FarmerReference')
    farmer_model = apps.get_model('supply_chains', 'Farmer')

    description = 'A unique identification number or code to identify members'

    # create Co-Operative Identification reference.
    ref = reference_model.objects.create(name='Co-Operative ID',
                                         description=description,
                                         is_editable=False)
    objs = []
    for farmer in farmer_model.objects.all():
        if farmer.identification_no:
            f_ref = farmer_reference_model(farmer_id=farmer.id,
                                           number=farmer.identification_no,
                                           reference=ref)
            objs.append(f_ref)
    farmer_reference_model.objects.bulk_create(objs, batch_size=100)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supply_chains', '0029_auto_20230327_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, null=True, upload_to=common.library._get_file_path)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_editable', models.BooleanField(default=True)),
                ('creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_reference_objects', to=settings.AUTH_USER_MODEL)),
                ('updater', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater_reference_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FarmerReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('number', models.CharField(max_length=20)),
                ('creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_farmerreference_objects', to=settings.AUTH_USER_MODEL)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply_chains.Farmer')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply_chains.Reference')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supply_chains.Company')),
                ('updater', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater_farmerreference_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
    ]
