# Generated by Django 2.2.6 on 2023-04-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chains', '0034_auto_20230411_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='consent_status',
            field=models.CharField(choices=[('GRANTED', 'GRANTED')], default='GRANTED', max_length=20),
        ),
    ]
