# Generated by Django 2.2.6 on 2023-04-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chains', '0035_farmer_consent_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='consent_status',
            field=models.CharField(choices=[('GRANTED', 'Consent Granted'), ('REVOKED', 'Consent Revoked'), ('UNKNOWN', 'Consent Unknown')], default='GRANTED', max_length=20),
        ),
    ]
