# Generated by Django 2.2.6 on 2023-07-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chains', '0038_auto_20230621_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='make_farmers_private',
            field=models.BooleanField(default=False),
        ),
    ]
