# Generated by Django 2.2.6 on 2023-09-06 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chains', '0039_company_make_farmers_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='income_from_main_product',
            field=models.FloatField(default=0.0),
        ),
    ]
