# Generated by Django 2.2.6 on 2023-09-07 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chains', '0040_auto_20230906_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='income_from_main_product',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
