# Generated by Django 2.2.6 on 2024-01-18 05:28

from django.db import migrations
import django_extensions.db.fields.json
import v2.supply_chains.validators


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chains', '0044_auto_20240117_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerplot',
            name='geo_json',
            field=django_extensions.db.fields.json.JSONField(blank=True, default=dict, null=True, validators=[v2.supply_chains.validators.validate_geojson_polygon, v2.supply_chains.validators.validate_coordinates]),
        ),
    ]
