# Generated by Django 2.2.6 on 2024-04-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chains', '0045_auto_20240118_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='sso_id',
            field=models.CharField(default='Not Available', max_length=100),
        ),
    ]
