# Generated by Django 2.2.6 on 2024-06-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chains', '0046_node_sso_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='sso_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
