# Generated by Django 2.2.6 on 2024-06-06 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chains', '0047_auto_20240605_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodefeatures',
            name='link_connect',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nodefeatures',
            name='link_navigate',
            field=models.BooleanField(default=False),
        ),
    ]
