# Generated by Django 2.2.6 on 2024-06-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chains', '0049_node_navigate_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerplot',
            name='sync_with_navigate',
            field=models.BooleanField(default=False),
        ),
    ]
