# Generated by Django 2.2.6 on 2024-12-02 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chains', '0050_farmerplot_sync_with_navigate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerreference',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_references', to='supply_chains.Farmer'),
        ),
    ]
