# Generated by Django 2.2.6 on 2025-01-07 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chains', '0051_auto_20241202_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerreference',
            name='farmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farmer_references', to='supply_chains.Farmer'),
        ),
    ]
