# Generated by Django 2.2.6 on 2025-06-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chains', '0052_auto_20250107_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockchainwallet',
            name='wallet_type',
            field=models.IntegerField(choices=[(101, 'TOPL'), (201, 'Hedera'), (301, 'Guardian')], default=201),
        ),
    ]
