# Generated by Django 2.2.6 on 2021-09-22 12:31
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_clientversion_userclientversion"),
    ]

    operations = [
        migrations.AddField(
            model_name="accesstoken",
            name="device",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.UserDevice",
            ),
        ),
    ]
