# Generated by Django 2.2.6 on 2021-10-04 22:20
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_accesstoken_device"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="id_no",
            field=models.CharField(
                blank=True, default="", max_length=100, null=True
            ),
        ),
    ]
