# Generated by Django 2.2.6 on 2022-12-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_person_id_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fairfooduser',
            name='type',
            field=models.IntegerField(choices=[(1, 'Node user'), (2, 'Fairfood admin'), (3, 'Fairfood manager')], default=1),
        ),
    ]
