# Generated by Django 2.2.6 on 2023-11-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20221221_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='fairfooduser',
            name='external_id',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
