# Generated by Django 2.2.6 on 2024-06-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_fairfooduser_sso_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fairfooduser',
            name='sso_user_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
