farmers = [
    {"name": "BENIMANA", "last": "Evariste"},
    {"name": "BWANAKEYE", "last": "Cassien"},
    {"name": "SINGLE ESTATE", "last": "xxxxxx"},
    {"name": "SINGLE ESTATE", "last": "xxxxxx"},
    {"name": "SINGLE ESTATE", "last": "xxxxxx"},
    {"name": "SINGLE ESTATE", "last": "xxxxxx"},
    {"name": "SINGLE ESTATE", "last": "xxxxxx"},
    {"name": "SINGLE ESTATE", "last": "xxxxxx"},
    {"name": "SINGLE ESTATE", "last": "xxxxxx"},
    {"name": "SINGLE ESTATE", "last": "xxxxxx"},
    {"name": "KALIBUHUNGU", "last": "Augustin"},
    {"name": "MUKAMUSONI", "last": "Veneranda"},
    {"name": "NDOLIYOBIJYA", "last": "Joseph"},
    {"name": "RWAMPFIZI", "last": "Fidele"},
    {"name": "UZABAKILIHO", "last": "Innocent"},
    {"name": "HAKIZIMANA", "last": "Innocent"},
    {"name": "SINGLE ESTATE", "last": "xxxxxx"},
    {"name": "MUHUTU", "last": "Joseph"},
    {"name": "MUKAMANA", "last": "Jeannette"},
    {"name": "MUKAMUSONI", "last": "Veneranda"},
    {"name": "MUNYAKAYANZA", "last": "Thelesphore"},
    {"name": "NZABAMWITA", "last": "Anastase"},
    {"name": "UZABAKILIHO", "last": "Innocent"},
    {"name": "UZABAKILIHO", "last": "Pascal"},
    {"name": "SINGLE ESTATE", "last": "xxxxxx"},
    {"name": "BWANAKEYE", "last": "Cassien"},
    {"name": "HAKIZINKA", "last": "Felicien"},
    {"name": "KALIBUHUNGU", "last": "Augustin"},
    {"name": "MUNYAKAYANZA", "last": "Thelesphore"},
    {"name": "NYIRAKAMANA", "last": "Annonciata"},
    {"name": "NYIRAMAJORO", "last": "Xaverine"},
    {"name": "RUYENZI", "last": "Charles"},
    {"name": "RWAMPFIZI", "last": "Fidele"},
    {"name": "UWIMANA", "last": "Seraphine"},
    {"name": "UWINGENEYE", "last": "Merise"},
    {"name": "UZABAKILIHO", "last": "Innocent"},
    {"name": "UZABAKILIHO", "last": "Pascal"},
    {"name": "SINGLE ESTATE", "last": "xxxxxx"},
    {"name": "BUGENIMANA", "last": "Eric"},
    {"name": "HAKIZINKA", "last": "Felicien"},
    {"name": "HAVUGIMANA", "last": "Nathanael"},
    {"name": "MUHUTU", "last": "Jeannette"},
    {"name": "MUKAMANA", "last": "Jeannette"},
    {"name": "MUKAMUSONI", "last": "Veneranda"},
    {"name": "NDIMUBANZI", "last": "Gratien"},
    {"name": "NYIRAMAJORO", "last": "Xaverine"},
    {"name": "NZABAMWITA", "last": "Anastase"},
    {"name": "RUKIMBIRA", "last": "Felicien"},
    {"name": "RUYENZI", "last": "Charles"},
    {"name": "UWINGENEYE", "last": "Merise"},
    {"name": "UZABAKILIHO", "last": "Pascal"},
    {"name": "ZIGAMA", "last": "Protais"},
    {"name": "ZILIMABAGABO", "last": "Jean Bosco"},
    {"name": "SINGLE ESTATE", "last": "xxxxxx"},
    {"name": "NIYIGENA", "last": "Lambert"},
    {"name": "RUTAYISIRE", "last": "J Pierre"},
    {"name": "SIBOMANA", "last": "J M Vianney"},
    {"name": "BUGENIMANA", "last": "Eric"},
    {"name": "BWANAKEYE", "last": "Cassien"},
    {"name": "GATETE", "last": "Jean Bosco"},
    {"name": "HABYALIMANA", "last": "Celestin"},
    {"name": "IYAMUREMYE", "last": "Jean"},
    {"name": "KALIBUHUNGU", "last": "Augustin"},
    {"name": "KWINDIRI", "last": "xxxxxx"},
    {"name": "MILINDI", "last": "Frank"},
    {"name": "MUKAMUSONI", "last": "Veneranda"},
    {"name": "MUNYAKAYANZA", "last": "Thelesphore"},
    {"name": "NSABIMANA", "last": "Alphonse"},
    {"name": "NTIGURIRWA", "last": "Sylvestre"},
    {"name": "NYIRANZAYOMVUGWA", "last": "Fortunee"},
    {"name": "NZABAMWITA", "last": "Anastase"},
    {"name": "NZABONIMPA", "last": "Jean Baptiste"},
    {"name": "RUKIMBIRA", "last": "Felicien"},
    {"name": "RWAMBONERA", "last": "Selvirien"},
    {"name": "RWAMPFIZI", "last": "Fidele"},
    {"name": "UWIMANA", "last": "Seraphine"},
    {"name": "UZABAKILIHO", "last": "Innocent"},
    {"name": "UZABAKILIHO", "last": "Pascal"},
    {"name": "SINGLE ESTATE", "last": "xxxxxx"},
    {"name": "BIZIMANA", "last": "Assumani"},
    {"name": "HAKIZIMANA", "last": "Innocent"},
    {"name": "KALIBUHUNGU", "last": "Augustin"},
    {"name": "KWINDIRI", "last": "xxxxxx"},
    {"name": "MBUZIHEREZO", "last": "Callixte"},
    {"name": "MUHUTU", "last": "Jean"},
    {"name": "MUKAMANA", "last": "Jeannette"},
    {"name": "MUKAMUSONI", "last": "Veneranda"},
    {"name": "MWONGEREZA", "last": "Jean d'Amour"},
    {"name": "MWUMVANEZA", "last": "Celestin"},
    {"name": "NDIMUBANZI", "last": "Gratien"},
    {"name": "NIYODUSABA", "last": "Sam"},
    {"name": "NYIRAKAMANA", "last": "Annonciata"},
    {"name": "NYIRAMAJORO", "last": "Xaverine"},
    {"name": "NZABAMWITA", "last": "Anastase"},
    {"name": "RUYENZI", "last": "Charles"},
    {"name": "UWIMANA", "last": "Seraphine"},
    {"name": "UZABAKILIHO", "last": "Innocent"},
    {"name": "UZABAKILIHO", "last": "Pascal"},
    {"name": "JIJUKA Cooperative", "last": "xxxxxx"},
    {"name": "SINGLE ESTATE", "last": "xxxxxx"},
    {"name": "BAJENEZA", "last": "J Claude"},
    {"name": "BENIMANA", "last": "Evariste"},
    {"name": "BWANAKEYE", "last": "Cassien"},
    {"name": "GAKURU", "last": "J Robert"},
    {"name": "HABYALIMANA", "last": "Celestin"},
    {"name": "HAKIZINKA", "last": "Felicien"},
    {"name": "IYAMUREMYE", "last": "Jean"},
    {"name": "KALIBUHUNGU", "last": "Augustin"},
    {"name": "KANYARWANDA", "last": "Augustin"},
    {"name": "MBUZIHEREZO", "last": "Callixte"},
    {"name": "MILINDI", "last": "Frank"},
    {"name": "MUKAMUSONI", "last": "Veneranda"},
    {"name": "MUNYAKAYANZA", "last": "Thelesphore"},
    {"name": "MUSABYEYEZU", "last": "Speciose"},
    {"name": "MWONGEREZA", "last": "J d'Amour"},
    {"name": "NTASONI", "last": "Desire"},
    {"name": "NTIGURIRWA", "last": "Sylvestre"},
    {"name": "NZABAMWITA", "last": "Anastase"},
    {"name": "NZABONIMPA", "last": "J Baptiste"},
    {"name": "RUKIMBIRA", "last": "Felicien"},
    {"name": "RWAMPFIZI", "last": "Fidele"},
    {"name": "UWINGENEYE", "last": "Merise"},
    {"name": "UZABAKILIHO", "last": "Innocent"},
    {"name": "UZABAKILIHO", "last": "Pascal"},
    {"name": "ZIGAMA", "last": "Protais"},
    {"name": "ZILIMABAGABO", "last": "J Bosco"},
    {"name": "SINGLE ESTATE", "last": "xxxxxx"},
    {"name": "BUGENIMANA", "last": "Eric"},
    {"name": "BWANAKEYE", "last": "Cassien"},
    {"name": "GATETE", "last": "J Bosco"},
    {"name": "HABIMANA", "last": "Evode"},
    {"name": "HABYALIMANA", "last": "Celestin"},
    {"name": "HAVUGIMANA", "last": "Nathanael"},
    {"name": "KALIBUHUNGU", "last": "Augustin"},
    {"name": "KANYARWANDA", "last": "Faustin"},
    {"name": "KWINDIRI", "last": "xxxxxx"},
    {"name": "MUHUTU", "last": "Jean"},
    {"name": "MUKAMANA", "last": "Jeannette"},
    {"name": "MUKAMUSONI", "last": "Veneranda"},
    {"name": "MUKANKUSI", "last": "Anastasie"},
    {"name": "MUKURALINDA", "last": "Innocent"},
    {"name": "MWUMVANEZA", "last": "Celestin"},
    {"name": "NDIMUBANZI", "last": "Gratien"},
    {"name": "NIYODUSABA", "last": "Sam"},
    {"name": "NSABIMANA", "last": "Alphonse"},
    {"name": "NTIGURIRWA", "last": "Sylvestre"},
    {"name": "NYIRAKAMANA", "last": "Annonciata"},
    {"name": "NYIRAMAJORO", "last": "Xaverine"},
    {"name": "NZABAMWITA", "last": "Anastase"},
    {"name": "NZABANDORA", "last": "Paulin"},
    {"name": "RUYENZI", "last": "Charles"},
    {"name": "RWAMBONERA", "last": "Selvirien"},
    {"name": "UZABAKILIHO", "last": "Pascal"},
    {"name": "RUTAYISIRE", "last": "J Pierre"},
    {"name": "SIBOMANA", "last": "J M Vianney"},
    {"name": "SINGLE ESTATE", "last": "xxxxxx"},
    {"name": "BAJENEZA", "last": "J Claude"},
    {"name": "BENIMANA", "last": "Evariste"},
    {"name": "BUGENIMANA", "last": "Eric"},
    {"name": "BWANAKEYE", "last": "Cassien"},
    {"name": "GATETE", "last": "J Bosco"},
    {"name": "HAKIZIMANA", "last": "Innocent"},
    {"name": "HAKIZINKA", "last": "Felicien"},
    {"name": "IYAMUREMYE", "last": "Jean"},
    {"name": "KALIBUHUNGU", "last": "Augustin"},
    {"name": "KANYESHOKI", "last": "Emmanuel"},
    {"name": "MBYALIYEHE", "last": "J Bosco"},
    {"name": "MILINDI", "last": "Frank"},
    {"name": "MUKAMUSONI", "last": "Veneranda"},
    {"name": "MUNYAKARAGWE", "last": "Gabriel"},
    {"name": "MUNYAKAYANZA", "last": "Thelesphore"},
    {"name": "MUSABYEYEZU", "last": "Speciose"},
    {"name": "MWONGEREZA", "last": "J d'Amour"},
    {"name": "NIIYOYITA", "last": "xxxxxx"},
    {"name": "NTASONI", "last": "Desire"},
    {"name": "NYIRANDAME", "last": "Aurelie"},
    {"name": "RUKIMBIRA", "last": "Felicien"},
    {"name": "RUYENZI", "last": "Charles"},
    {"name": "RWAMPFIZI", "last": "Fidele"},
    {"name": "UBALIJORO", "last": "Xaveri"},
    {"name": "UWIMANA", "last": "Seraphine"},
    {"name": "UWINGENEYE", "last": "Merise"},
    {"name": "UZABAKILIHO", "last": "Innocent"},
    {"name": "UZABAKILIHO", "last": "Pascal"},
    {"name": "ZILIMABAGABO", "last": "J Bosco"},
    {"name": "SINGLE ESTATE", "last": "xxxxxx"},
    {"name": "BENIMANA", "last": "Evariste"},
    {"name": "BWANAKEYE", "last": "Cassien"},
    {"name": "GAKURU", "last": "J Robert"},
    {"name": "HAVUGIMANA", "last": "Nathanael"},
    {"name": "KALIBUHUNGU", "last": "Augustin"},
    {"name": "KALISA", "last": "J Damascene"},
    {"name": "KIMONYO", "last": "Augustin"},
    {"name": "MUKAMANA", "last": "Jeannette"},
    {"name": "MUKAMUSONI", "last": "Veneranda"},
    {"name": "MUKANKUSI", "last": "Anastasie"},
    {"name": "MUKURALINDA", "last": "Innocent"},
    {"name": "MUNYAKAYANZA", "last": "Thelesphore"},
    {"name": "NGEZAHAYO", "last": "Thelesphore"},
    {"name": "NTAMBARA", "last": "Daniel"},
    {"name": "NYIRANZAYOMVUGWA", "last": "Fortunee"},
    {"name": "NZABAMWITA", "last": "Anastase"},
    {"name": "NZABANDORA", "last": "Paulin"},
    {"name": "NZABONIMPA", "last": "J Baptiste"},
    {"name": "RWAMBONERA", "last": "Selvirien"},
    {"name": "RWAMPFIZI", "last": "Fidele"},
    {"name": "UWIZEYIMANA", "last": "Felicien"},
    {"name": "UZABAKILIHO", "last": "Innocent"},
    {"name": "UZABAKILIHO", "last": "Pascal"},
    {"name": "NIYIGENA", "last": "Lambert"},
    {"name": "SINGLE ESTATE", "last": "xxxxxx"},
    {"name": "BAJENEZA", "last": "J Claude"},
    {"name": "BUGENIMANA", "last": "Eric"},
    {"name": "BWANAKEYE", "last": "Cassien"},
    {"name": "GATABAZI", "last": "Isdore"},
    {"name": "GATETE", "last": "J Bosco"},
    {"name": "GATSINZI", "last": "Anastase"},
    {"name": "HABIMANA", "last": "Evode"},
    {"name": "HABYALIMANA", "last": "Celestin"},
    {"name": "HAKIZINKA", "last": "Felicien"},
    {"name": "HAVUGIMANA", "last": "Nathanael"},
    {"name": "KALIBUHUNGU", "last": "Augustin"},
    {"name": "KANYARWANDA", "last": "Faustin"},
    {"name": "KWINDIRI", "last": "xxxxxx"},
    {"name": "MANIRAGABA", "last": "Valens"},
    {"name": "MBUZIHEREZO", "last": "Callixte"},
    {"name": "MILINDA", "last": "Frank"},
    {"name": "MUHUTU", "last": "Jean"},
    {"name": "MUKAMUSONI", "last": "Veneranda"},
    {"name": "MUNYAKARAGWE", "last": "Gabriel"},
    {"name": "MUSABYEYEZU", "last": "Speciose"},
    {"name": "MUSESARUGAMBA", "last": "Francois"},
    {"name": "MWONGEREZA", "last": "J d'Amour"},
    {"name": "NDOLIYOBIJYA", "last": "Joseph"},
    {"name": "NIYODUSABA", "last": "Sam"},
    {"name": "NTIGURIRWA", "last": "Sylvestre"},
    {"name": "NYIRAKAMANA", "last": "Annonciata"},
    {"name": "NYIRAMAJORO", "last": "Xaverina"},
    {"name": "NZABAMWITA", "last": "Anastase"},
    {"name": "RUGARAVU", "last": "Faustin"},
    {"name": "UBALIJORO", "last": "Xaveri"},
    {"name": "UZABAKILIHO", "last": "Emmanuel"},
    {"name": "UZABAKILIHO", "last": "Innocent"},
    {"name": "UZABAKILIHO", "last": "Pascal"},
    {"name": "ZIGAMA", "last": "Protais"},
    {"name": "NIYIGABA", "last": "Lambert"},
    {"name": "SINGLE ESTATE", "last": "xxxxxx"},
    {"name": "AYIRWANDA", "last": "Frederick"},
    {"name": "BAJENEZA", "last": "J Claude"},
    {"name": "BENIMANA", "last": "Evariste"},
    {"name": "GATABAZI", "last": "Isdore"},
    {"name": "GATETE", "last": "J Bosco"},
    {"name": "HAKIZIMANA", "last": "Aloys"},
    {"name": "HAKIZIMANA", "last": "Innocent"},
    {"name": "HAKIZINKA", "last": "Felicien"},
    {"name": "IYAKAREMYE", "last": "James"},
    {"name": "KALIBUHUNGU", "last": "Augustin"},
    {"name": "KAZIMBAYA", "last": "Christophe"},
    {"name": "KIMONYO", "last": "Augustin"},
    {"name": "MBYALIYEHE", "last": "J Bosco"},
    {"name": "MILINDI", "last": "Frank"},
    {"name": "MUKAMANA", "last": "Jeannette"},
    {"name": "MUKAMUSONI", "last": "Veneranda"},
    {"name": "MUKANKUSI", "last": "Anastasie"},
    {"name": "MUKURALINDA", "last": "Innocent"},
    {"name": "MUNYAKAYANZA", "last": "Thelesphore"},
    {"name": "MUNYAZESA", "last": "Charles"},
    {"name": "NDABABONYE", "last": "Gervais"},
    {"name": "NIYOYITA", "last": "xxxxxx"},
    {"name": "NSABIMANA", "last": "Alphonse"},
    {"name": "NTASONI", "last": "Desire"},
    {"name": "NYIRAMAJORO", "last": "Xaverine"},
    {"name": "NZABAMWITA", "last": "Anastase"},
    {"name": "NZABONIMPA", "last": "J Baptiste"},
    {"name": "RUKIMBIRA", "last": "Felicien"},
    {"name": "RUYENZI", "last": "Charles"},
    {"name": "RWAMBONERA", "last": "Selvirien"},
    {"name": "RWAMPFIZI", "last": "Fidele"},
    {"name": "SIBOMANA", "last": "Janvier"},
    {"name": "UZABAKILIHO", "last": "Pascal"},
    {"name": "ZILIMABAGABO", "last": "J Bosco"},
    {"name": "NIYIGABA", "last": "Lambert"},
    {"name": "SINGLE ESTATE", "last": "xxxxxx"},
    {"name": "BAJENEZA", "last": "J Claude"},
    {"name": "BIRINDA", "last": "Faustin"},
    {"name": "BUGENIMANA", "last": "Eric"},
    {"name": "BWANAKEYE", "last": "Cassien"},
    {"name": "GAKURU", "last": "J Robert"},
    {"name": "IYAMUREMYE", "last": "Jean"},
    {"name": "KALIBUHUNGU", "last": "Augustin"},
    {"name": "KALISA", "last": "J Damascene"},
    {"name": "KANYARWANDA", "last": "Faustin"},
    {"name": "KANYESHOKI", "last": "Emmanuel"},
    {"name": "KWINDIRI", "last": "xxxxxx"},
    {"name": "KWINDIRI", "last": "xxxxxx"},
    {"name": "MUKESHIMANA", "last": "xxxxxx"},
    {"name": "MUSABYEYEZU", "last": "Esperance"},
    {"name": "MWONGEREZA", "last": "J d'Amour"},
    {"name": "NDIMUBANZI", "last": "Gratien"},
    {"name": "NDOLIYOBIJYA", "last": "Joseph"},
    {"name": "NTAMBARA", "last": "Daniel"},
    {"name": "NYIRANZAYOMVUGWA", "last": "Fortunee"},
    {"name": "RUGARAVU", "last": "Faustin"},
    {"name": "RWAMBONERA", "last": "Selvirien"},
    {"name": "UBALIJORO", "last": "Xaveri"},
    {"name": "UWIMANA", "last": "Seraphine"},
    {"name": "UZABAKILIHO", "last": "Emmanuel"},
    {"name": "UZABAKILIHO", "last": "Innocent"},
    {"name": "UZABAKILIHO", "last": "Pascal"},
    {"name": "SINGLE ESTATE", "last": "xxxxxx"},
    {"name": "AYIRWANDA", "last": "Frederick"},
    {"name": "BAJENEZA", "last": "J Claude"},
    {"name": "BENIMANA", "last": "Evariste"},
    {"name": "BUHIGIRO", "last": "Leopold"},
    {"name": "BUTARE", "last": "Fidele"},
    {"name": "GATABAZI", "last": "Isdore"},
    {"name": "GATETE", "last": "J Bosco"},
    {"name": "IYAMUREMYE", "last": "James"},
    {"name": "KALIBUHUNGU", "last": "Augustin"},
    {"name": "KIMONYO", "last": "Augustin"},
    {"name": "MBUZIHEREZO", "last": "Callixte"},
    {"name": "MBYALIYEHE", "last": "J Bosco"},
    {"name": "MILINDI", "last": "Frank"},
    {"name": "MUHUTU", "last": "Jean"},
    {"name": "MUKAMUSONI", "last": "Veneranda"},
    {"name": "MUKANKUSI", "last": "Anastasie"},
    {"name": "MUKURALINDA", "last": "Innocent"},
    {"name": "MUNYAKARAGWE", "last": "Gabriel"},
    {"name": "MUNYAZESA", "last": "Charles"},
    {"name": "MUSABYIMANA", "last": "Cyprien"},
    {"name": "MUSESARUGAMBA", "last": "Francois"},
    {"name": "MWONGEREZA", "last": "J d'Amour"},
    {"name": "MWUMVANEZA", "last": "Celestin"},
    {"name": "NDABABONYE", "last": "Gervais"},
    {"name": "NYIRANDAME", "last": "Aurelie"},
    {"name": "NZABAMWITA", "last": "Anastase"},
    {"name": "NZABONIMPA", "last": "J Baptiste"},
    {"name": "RUKIMBIRA", "last": "Felicien"},
    {"name": "RUYENZI", "last": "Charles"},
    {"name": "UWINGENEYE", "last": "Merise"},
    {"name": "UZABAKILIHO", "last": "Innocent"},
    {"name": "UZABAKILIHO", "last": "Pascal"},
    {"name": "ZIGAMA", "last": "Protais"},
    {"name": "JIJUKA Cooperative", "last": "xxxxxx"},
    {"name": "SINGLE ESTATE", "last": "xxxxxx"},
    {"name": "BAJENEZA", "last": "J Claude"},
    {"name": "BUGENIMANA", "last": "Eric"},
    {"name": "BWANAKEYE", "last": "Cassien"},
    {"name": "HAKIZIMANA", "last": "Innocent"},
    {"name": "HAKOLIMANA", "last": "Xaveri"},
    {"name": "HAVUGIMANA", "last": "Nathanael"},
    {"name": "IYAMUREMYE", "last": "Jean"},
    {"name": "KALIBUHUNGU", "last": "Augustin"},
    {"name": "KALISA", "last": "J Damascene"},
    {"name": "KANYESHOKI", "last": "Emmanuel"},
    {"name": "KAZIMBAYA", "last": "Christophe"},
    {"name": "KIMONYO", "last": "Augustin"},
    {"name": "MUKAMANA", "last": "Jeannette"},
    {"name": "MUKAMUSONI", "last": "Veneranda"},
    {"name": "MUNYAKAYANZA", "last": "Thelesphore"},
    {"name": "MUSABYEYEZU", "last": "Speciose"},
    {"name": "MUTSINZI", "last": "Andre"},
    {"name": "NDOLIYOBIJYA", "last": "Joseph"},
    {"name": "NGEZAHAYO", "last": "Thelesphore"},
    {"name": "NIYODUSABA", "last": "Sam"},
    {"name": "NTEZIRYAYO", "last": "Alexandre"},
    {"name": "NTIGURIRWA", "last": "Sylvestre"},
    {"name": "NYIRAKAMANA", "last": "Annonciata"},
    {"name": "NYIRAMAJORO", "last": "Xaverine"},
    {"name": "RUGARAVU", "last": "Faustin"},
    {"name": "RUKIMBIRA", "last": "Felicien"},
    {"name": "RWAMBONERA", "last": "Selvirien"},
    {"name": "UWIZEYIMANA", "last": "Felicien"},
    {"name": "UZABAKILIHO", "last": "Pascal"},
    {"name": "ZILIMABAGABO", "last": "J Bosco"},
    {"name": "SINGLE ESTATE", "last": "xxxxxx"},
    {"name": "AYIRWANDA", "last": "Frederick"},
    {"name": "BAJENEZA", "last": "J Claude"},
    {"name": "BENIMANA", "last": "Evariste"},
    {"name": "BIRINDA", "last": "Faustin"},
    {"name": "BUGENIMANA", "last": "Eric"},
    {"name": "GATSINZI", "last": "Anastase"},
    {"name": "HABYALIMANA", "last": "Celestin"},
    {"name": "HAKIZIMANA", "last": "Innocent"},
    {"name": "HAKIZINKA", "last": "Felicien"},
    {"name": "KALIBUHUNGU", "last": "Augustin"},
    {"name": "KANYARWANDA", "last": "Faustin"},
    {"name": "KWINDIRI", "last": "xxxxxx"},
    {"name": "MANIRAGABA", "last": "Valens"},
    {"name": "MBYALIYEHE", "last": "J Bosco"},
    {"name": "MILINDI", "last": "Frank"},
    {"name": "MUHUTU", "last": "Jean"},
    {"name": "MUKAMUSONI", "last": "Veneranda"},
    {"name": "MUKANKUSI", "last": "Anastasie"},
    {"name": "MUKESHIMANA", "last": "xxxxxx"},
    {"name": "MUKURALINDA", "last": "Innocent"},
    {"name": "MUNGANYINKA", "last": "Desire"},
    {"name": "MUNYAKAYANZA", "last": "Thelesphore"},
    {"name": "MUNYAZESA", "last": "Charles"},
    {"name": "MUSABYIMANA", "last": "Cyprien"},
    {"name": "NDABABONYE", "last": "Gervais"},
    {"name": "NDIMUBANZI", "last": "Gratien"},
    {"name": "NDOLIYOBIJYA", "last": "Joseph"},
    {"name": "NSABIMANA", "last": "Alphonse"},
    {"name": "NTAMBARA", "last": "Daniel"},
    {"name": "NZABAMWITA", "last": "Anastase"},
    {"name": "RUGARAVU", "last": "Faustin"},
    {"name": "RUKIMBIRA", "last": "Felicien"},
    {"name": "RUYENZI", "last": "Charles"},
    {"name": "RWAMBONERA", "last": "Selvirien"},
    {"name": "SIBOMANA", "last": "Janvier"},
    {"name": "UWIZEYIMANA", "last": "Felicien"},
    {"name": "UZABAKILIHO", "last": "Emmanuel"},
    {"name": "UZABAKILIHO", "last": "Innocent"},
    {"name": "UZABAKILIHO", "last": "Pascal"},
    {"name": "ZIGAMA", "last": "Protais"},
    {"name": "ZIHINJISHI", "last": "Xaverine"},
    {"name": "RUTAYISIRE", "last": "J Pierre"},
    {"name": "SIBOMANA", "last": "JM Vianney"},
    {"name": "SINGLE ESTATE", "last": "xxxxxx"},
    {"name": "BAJENEZA", "last": "J Claude"},
    {"name": "BENIMANA", "last": "Evariste"},
    {"name": "BUHIGIRO", "last": "Leopold"},
    {"name": "BWANAKEYE", "last": "Cassien"},
    {"name": "GAKURU", "last": "J Robert"},
    {"name": "HAKIZIMANA", "last": "Aloys"},
    {"name": "HAKIZINKA", "last": "Felicien"},
    {"name": "IYAMUREMYE", "last": "Jean"},
    {"name": "KALISA", "last": "J Damascene"},
    {"name": "KANYESHOKI", "last": "Emmanuel"},
    {"name": "KAZIMBAYA", "last": "Christophe"},
    {"name": "KWINDIRI", "last": "xxxxxx"},
    {"name": "MUKAMUSONI", "last": "Veneranda"},
    {"name": "MUNYAKAYANZA", "last": "Thelesphore"},
    {"name": "MUSABYEYEZU", "last": "Speciose"},
    {"name": "MUTSINZI", "last": "Andre"},
    {"name": "NGEZAHAYO", "last": "Thelesphore"},
    {"name": "NIYOYITA", "last": "xxxxxx"},
    {"name": "NTASONI", "last": "Desire"},
    {"name": "NTEZIRYAYO", "last": "Alexandre"},
    {"name": "NYIRANDAME", "last": "Aurelie"},
    {"name": "NZABANDORA", "last": "Paulin"},
    {"name": "NZABONIMPA", "last": "J Baptiste"},
    {"name": "RUYENZI", "last": "Charles"},
    {"name": "UWINGENEYE", "last": "Merise"},
    {"name": "UZABAKILIHO", "last": "Innocent"},
    {"name": "UZABAKILIHO", "last": "Pascal"},
    {"name": "NIYIGABA", "last": "Lambert"},
    {"name": "SINGLE ESTATE", "last": "xxxxxx"},
    {"name": "BAJENEZA", "last": "J Claude"},
    {"name": "BENIMANA", "last": "Evariste"},
    {"name": "BUGENIMANA", "last": "Eric"},
    {"name": "BUTARE", "last": "Fidele"},
    {"name": "BWANAKEYE", "last": "Cassien"},
    {"name": "HABIMANA", "last": "Evode"},
    {"name": "HAKIZIMANA", "last": "Aloys"},
    {"name": "HAKOLIMANA", "last": "Xavier"},
    {"name": "HAVUGIMANA", "last": "Nathanael"},
    {"name": "IYAMUREMYE", "last": "James"},
    {"name": "KALIBUHUNGU", "last": "Augustin"},
    {"name": "KANYARWANDA", "last": "Faustin"},
    {"name": "KIMONYO", "last": "Augustin"},
    {"name": "MANIRAGABA", "last": "Valens"},
    {"name": "KWINDIRI", "last": "xxxxxx"},
    {"name": "MBUZIHEREZO", "last": "Callixte"},
    {"name": "MUHUTU", "last": "Jean"},
    {"name": "MUKAMUSONI", "last": "Veneranda"},
    {"name": "MUKESHIMANA", "last": "xxxxxx"},
    {"name": "MUNGANYINKA", "last": "Desire"},
    {"name": "MUNYAKARAGWE", "last": "Gabriel"},
    {"name": "MUSABYIMANA", "last": "Cyprien"},
    {"name": "MUSESARUGAMBA", "last": "Francois"},
    {"name": "MUTSINZI", "last": "Andre"},
    {"name": "MWONGEREZA", "last": "J d'Amour"},
    {"name": "NDABABONYE", "last": "Gervais"},
    {"name": "NTAMBARA", "last": "Daniel"},
    {"name": "NYIRAMAJORO", "last": "Xaverine"},
    {"name": "NZABONIMPA", "last": "J Baptiste"},
    {"name": "RUGARAVU", "last": "Faustin"},
    {"name": "RUKIMBIRA", "last": "Felicien"},
    {"name": "RUYENZI", "last": "Charles"},
    {"name": "RWAMBONERA", "last": "Selvirien"},
    {"name": "UBALIJORO", "last": "Xavier"},
    {"name": "UWIZEYIMANA", "last": "Felicien"},
    {"name": "UZABAKILIHO", "last": "Innocent"},
    {"name": "UZABAKILIHO", "last": "Pascal"},
    {"name": "ZIGAMA", "last": "Protais"},
    {"name": "NIYIGABA", "last": "Lambert"},
    {"name": "SINGLE ESTATE", "last": "xxxxxx"},
    {"name": "BAZIHIZINA", "last": "Anastasie"},
    {"name": "BENIMANA", "last": "Evariste"},
    {"name": "BIZIMANA", "last": "Assumani"},
    {"name": "BUHIGIRO", "last": "Leopold"},
    {"name": "BUTARE", "last": "Fidele"},
    {"name": "GAKURU", "last": "J Robert"},
    {"name": "HAKIZIMANA", "last": "Aloys"},
    {"name": "HAKIZIMANA", "last": "Innocent"},
    {"name": "HAKIZINKA", "last": "Felicien"},
    {"name": "HAKOLIMANA", "last": "Xavier"},
    {"name": "IYAMUREMYE", "last": "Jean"},
    {"name": "KALIBUHUNGU", "last": "Augustin"},
    {"name": "MUKAMANA", "last": "Jeannette"},
    {"name": "MUKURALINDA", "last": "Innocent"},
    {"name": "MUSESARUGAMBA", "last": "Francois"},
    {"name": "MWONGEREZA", "last": "J d'Amour"},
    {"name": "NDIMUBANZI", "last": "Gratien"},
    {"name": "NIYODUSABA", "last": "Sam"},
    {"name": "NTIGURIRWA", "last": "Sylvestre"},
    {"name": "NYIRANDAME", "last": "Aurelie"},
    {"name": "NZABAMWITA", "last": "Anastase"},
    {"name": "RWAMBONERA", "last": "Selvirien"},
    {"name": "UWIMANA", "last": "Seraphine"},
    {"name": "UZABAKILIHO", "last": "Emmanuel"},
    {"name": "UZABAKILIHO", "last": "Innocent"},
    {"name": "ZILIMABAGABO", "last": "J Bosco"},
    {"name": "NIYIGABA", "last": "Lambert"},
    {"name": "SINGLE ESTATE", "last": "xxxxxx"},
    {"name": "AYIRWANDA", "last": "Frederick"},
    {"name": "BAJENEZA", "last": "J Claude"},
    {"name": "BAZIHIZINA", "last": "Anastasie"},
    {"name": "BENIMANA", "last": "Evariste"},
    {"name": "BILINDA", "last": "Faustin"},
    {"name": "BUGENIMANA", "last": "Eric"},
    {"name": "BUHIGIRO", "last": "Leopold"},
    {"name": "BUTARE", "last": "Fidele"},
    {"name": "GAKURU", "last": "J Robert"},
    {"name": "GATABAZI", "last": "Isdore"},
    {"name": "GATETE", "last": "J Bosco"},
    {"name": "GATSINZI", "last": "Anastase"},
    {"name": "HAKIZINKA", "last": "Felicien"},
    {"name": "IYAKAREMYE", "last": "James"},
    {"name": "KALIBUHUNGU", "last": "Augustin"},
    {"name": "KANYARWANDA", "last": "Faustin"},
    {"name": "MANIRAGABA", "last": "Valens"},
    {"name": "MBYALIYEHE", "last": "J Bosco"},
    {"name": "MUHUTU", "last": "Jean"},
    {"name": "MUKAMUSONI", "last": "Veneranda"},
    {"name": "MUNYAKARAGWE", "last": "Gabriel"},
    {"name": "MUNYAKAYANZA", "last": "Thelesphore"},
    {"name": "MUTSINZI", "last": "Andre"},
    {"name": "MWONGEREZA", "last": "J d'Amour"},
    {"name": "NDIMUBANZI", "last": "Gratien"},
    {"name": "NDOLIYOBIJYA", "last": "Joseph"},
    {"name": "NTEZIRYAYO", "last": "Alexandre"},
    {"name": "NYIRAMAJORO", "last": "Xaverine"},
    {"name": "NZABAMWITA", "last": "Anastase"},
    {"name": "RUKIMBIRA", "last": "Felicien"},
    {"name": "UWINGENEYE", "last": "Merise"},
    {"name": "UWIZEYIMANA", "last": "Felicien"},
    {"name": "UZABAKILIHO", "last": "Emmanuel"},
    {"name": "UZABAKILIHO", "last": "Innocent"},
    {"name": "UZABAKILIHO", "last": "Pascal"},
    {"name": "ZILIMABAGABO", "last": "J Bosco"},
    {"name": "NIYIGABA", "last": "Lambert"},
    {"name": "JIJUKA Cooperative", "last": "xxxxxx"},
    {"name": "AYIRWANDA", "last": "Frederick"},
    {"name": "BAJENEZA", "last": "Jean Claude"},
    {"name": "GAKURU", "last": "Jean Robert"},
    {"name": "GATABAZI", "last": "Isdore"},
    {"name": "GATSINZI", "last": "Anastase"},
    {"name": "HABIMANA", "last": "Evode"},
    {"name": "IYAMUREMYE", "last": "Jean"},
    {"name": "KALIBUHUNGU", "last": "Augustin"},
    {"name": "KIMONYO", "last": "Augustin"},
    {"name": "MBUZIHEREZO", "last": "Callixte"},
    {"name": "MUKAMUSONI", "last": "Veneranda"},
    {"name": "MUNYAKARAGWE", "last": "Gabriel"},
    {"name": "MUTSINZI", "last": "Andre"},
    {"name": "NYIRAMAJORO", "last": "Xaverine"},
    {"name": "NZABAMWITA", "last": "Anastase"},
    {"name": "RUYENZI", "last": "Charles"},
    {"name": "UZABAKILIHO", "last": "Pascal"},
    {"name": "SINGLE ESTATE", "last": "xxxxxx"},
    {"name": "BUHIGIRO", "last": "Leopold"},
    {"name": "BWANAKEYE", "last": "Cassien"},
    {"name": "MUKAMANA", "last": "Jeannette"},
    {"name": "MUKAMUSONI", "last": "Veneranda"},
    {"name": "MUNYAKAYANZA", "last": "Thelesphore"},
    {"name": "NDIMUBANZI", "last": "Gratien"},
    {"name": "NGEZAHAYO", "last": "Thelesphore"},
    {"name": "RUKIMBIRA", "last": "Felicien"},
    {"name": "SIBOMANA", "last": "Janvier"},
    {"name": "ZIGAMA", "last": "Protais"},
    {"name": "ZILIMABAGABO", "last": "J Bosco"},
    {"name": "SINGLE ESTATE", "last": "xxxxxx"},
    {"name": "BAZIHIZINA", "last": "Anastase"},
    {"name": "BUGENIMANA", "last": "Eric"},
    {"name": "KALIBUHUNGU", "last": "Augustin"},
    {"name": "MANIRAGABA", "last": "Valens"},
    {"name": "MILINDI", "last": "Frank"},
    {"name": "MUKAMANA", "last": "Jeannette"},
    {"name": "MUKAMUSONI", "last": "Veneranda"},
    {"name": "MUSABYIMANA", "last": "Cyprien"},
    {"name": "MUSESARUGAMBA", "last": "Francois"},
    {"name": "MWONGEREZA", "last": "Jean d'Amour"},
    {"name": "NDABABONYE", "last": "Gervais"},
    {"name": "NZABONIMPA", "last": "Jean Baptiste"},
    {"name": "RUKIMBIRA", "last": "Felicien"},
    {"name": "RWAMBONERA", "last": "Selvirien"},
    {"name": "RWAMPFIZI", "last": "Fidele"},
    {"name": "UWIZEYIMANA", "last": "Felicien"},
    {"name": "UZABAKILIHO", "last": "Pascal"},
    {"name": "ZIHINJISHI", "last": "Laurence"},
    {"name": "SINGLE ESTATE", "last": "xxxxxx"},
    {"name": "NIYIGABA", "last": "Lambert"},
    {"name": "BENIMANA", "last": "Evariste"},
    {"name": "BUGENIMANA", "last": "Eric"},
    {"name": "GATABAZI", "last": "Isdore"},
    {"name": "HAKIZIMANA", "last": "Innocent"},
    {"name": "KANYARWANDA", "last": "Faustin"},
    {"name": "MUHUTU", "last": "Jean"},
    {"name": "MUKANKUSI", "last": "Anastasie"},
    {"name": "MUSABYEYEZU", "last": "Speciose"},
    {"name": "NDOLIYOBIJYA", "last": "Joseph"},
    {"name": "NTASONI", "last": "Desire"},
    {"name": "NTEZIRYAYO", "last": "Alexandre"},
    {"name": "NYIRANDAME", "last": "Aurelie"},
    {"name": "NZABANDORA", "last": "Paulin"},
    {"name": "RUGARAVU", "last": "Faustin"},
    {"name": "RWAMPFIZI", "last": "Fidele"},
    {"name": "UWINGENEYE", "last": "Merise"},
    {"name": "UZABAKILIHO", "last": "Emmanuel"},
    {"name": "UZABAKILIHO", "last": "Innocent"},
    {"name": "SINGLE ESTATE", "last": "xxxxxx"},
    {"name": "NIYIGABA", "last": "Lambert"},
    {"name": "BENIMANA", "last": "Evariste"},
    {"name": "BIZIMANA", "last": "Assumani"},
    {"name": "HAKIZIMANA", "last": "Innocent"},
    {"name": "HAKIZINKA", "last": "Felicien"},
    {"name": "KWINDIRI", "last": "xxxxxx"},
    {"name": "MUKAMUSONI", "last": "Veneranda"},
    {"name": "NIYOYITA", "last": "xxxxxx"},
    {"name": "NTEZIRYAYO", "last": "Sylvestre"},
    {"name": "RUYENZI", "last": "Charles"},
    {"name": "RWAMPFIZI", "last": "Fidele"},
    {"name": "UZABAKILIHO", "last": "Innocent"},
    {"name": "SINGLE ESTATE", "last": "xxxxxx"},
    {"name": "NIYIGABA", "last": "Lambert"},
    {"name": "AYIRWANDA", "last": "Frederick"},
    {"name": "BAJENEZA", "last": "J Claude"},
    {"name": "BWANAKEYE", "last": "Cassien"},
    {"name": "GATSINZI", "last": "Anastase"},
    {"name": "HABYALIMANA", "last": "Celestin"},
    {"name": "KALIBUHUNGU", "last": "Augustin"},
    {"name": "KANYESHOKI", "last": "Emmanuel"},
    {"name": "NGEZAHAYO", "last": "Thelesphore"},
    {"name": "NIYODUSABA", "last": "Sam"},
    {"name": "NTAMBARA", "last": "Daniel"},
    {"name": "NYIRAMAJORO", "last": "Xaverine"},
    {"name": "NYIRANZAYOMVUGWA", "last": "Fortunee"},
    {"name": "RUYENZI", "last": "Charles"},
    {"name": "SIBOMANA", "last": "Janvier"},
    {"name": "UWIMANA", "last": "Seraphine"},
    {"name": "UZABAKILIHO", "last": "Pascal"},
    {"name": "ZIGAMA", "last": "Protais"},
    {"name": "SINGLE ESTATE", "last": "xxxxxx"},
    {"name": "NIYIGABA", "last": "Lambert"},
    {"name": "BAJENEZA", "last": "J Claude"},
    {"name": "BAZIHIZINA", "last": "Anastase"},
    {"name": "BIRINDA", "last": "Faustin"},
    {"name": "BUTARE", "last": "Fidele"},
    {"name": "KALIBUHUNGU", "last": "Augustin"},
    {"name": "MWONGEREZA", "last": "Jean d'Amour"},
    {"name": "NDIMUBANZI", "last": "Gratien"},
    {"name": "NSABIMANA", "last": "Alphonse"},
    {"name": "NYIRAKAMANA", "last": "Annonciata"},
    {"name": "NZABAMWITA", "last": "Anastase"},
    {"name": "RUKIMBIRA", "last": "Felicien"},
    {"name": "UZABAKILIHO", "last": "Pascal"},
    {"name": "SINGLE ESTATE", "last": "xxxxxx"},
    {"name": "GAKURU", "last": "Jean Robert"},
    {"name": "GATETE", "last": "J Bosco"},
    {"name": "HABIMANA", "last": "Evode"},
    {"name": "KALIBUHUNGU", "last": "Augustin"},
    {"name": "KIMONYO", "last": "Augustin"},
    {"name": "MBUZIHEREZO", "last": "Callixte"},
    {"name": "MUKAMUSONI", "last": "Veneranda"},
    {"name": "MUNGANYINKA", "last": "Denise"},
    {"name": "MUNYAKAYANZA", "last": "Thelesphore"},
    {"name": "MUNYAZESA", "last": "Charles"},
    {"name": "NTEZIRYAYO", "last": "Alexandre"},
    {"name": "NTIGURIRWA", "last": "Sylvestre"},
    {"name": "NZABAMWITA", "last": "Anastase"},
    {"name": "RWAMBONERA", "last": "Selvirien"},
    {"name": "UWIZEYIMANA", "last": "Felicien"},
    {"name": "ZILIMABAGABO", "last": "J Bosco"},
    {"name": "AYIRWANDA", "last": "Frederick"},
    {"name": "BWANAKEYE", "last": "Cassien"},
    {"name": "HAKIZIMANA", "last": "Aloys"},
    {"name": "HAKIZINKA", "last": "Felicien"},
    {"name": "IYAKAREMYE", "last": "James"},
    {"name": "MUKAMANA", "last": "Jeannette"},
    {"name": "MUKAMUSONI", "last": "Veneranda"},
    {"name": "NYIRAMAJORO", "last": "Xaverine"},
    {"name": "UZABAKILIHO", "last": "Emmanuel"},
    {"name": "ZILIMABAGABO", "last": "J Bosco"},
    {"name": "SINGLE ESTATE", "last": "xxxxxx"},
    {"name": "JIJUKA Cooperative", "last": "xxxxxx"},
    {"name": "KANYARWANDA", "last": "Faustin"},
    {"name": "MILINDI", "last": "Frank"},
    {"name": "MUNYAKARAGWE", "last": "Gabriel"},
    {"name": "MUSESARUGAMBA", "last": "Francois"},
    {"name": "NDOLIYOBIJYA", "last": "Joseph"},
    {"name": "NSABIMANA", "last": "Alphonse"},
    {"name": "NTASONI", "last": "Desire"},
    {"name": "NYIRANDAME", "last": "Aurelie"},
    {"name": "NZABONIMPA", "last": "J Baptiste"},
    {"name": "RWAMPFIZI", "last": "Fidele"},
    {"name": "UBALIJORO", "last": "Xavier"},
    {"name": "UZABAKILIHO", "last": "Pascal"},
    {"name": "BUGENIMANA", "last": "Eric"},
    {"name": "GATABAZI", "last": "Isdore"},
    {"name": "GATSINZI", "last": "Anastase"},
    {"name": "KALIBUHUNGU", "last": "Augustin"},
    {"name": "KAZIMBAYA", "last": "Christophe"},
    {"name": "KWINDIRI (2)", "last": "xxxxxx"},
    {"name": "MUKAMUSONI", "last": "Veneranda"},
    {"name": "MUKURALINDA", "last": "Innocent"},
    {"name": "MWONGEREZA", "last": "Jean d'Amour"},
    {"name": "NGEZAHAYO", "last": "Thelesphore"},
    {"name": "NIYOYITA", "last": "xxxxxx"},
    {"name": "NYIRAKAMANA", "last": "Annonciata"},
    {"name": "NYIRANZAYOMVUGWA", "last": "Fortunee"},
    {"name": "NZABANDORA", "last": "Paulin"},
    {"name": "NIYIGABA", "last": "Lambert"},
    {"name": "AYIRWANDA", "last": "Frederick"},
    {"name": "HAKIZIMANA", "last": "Innocent"},
    {"name": "MUHUTU", "last": "Jean"},
    {"name": "MUTSINZI", "last": "Andre"},
    {"name": "MWONGEREZA", "last": "Jean d'Amour"},
    {"name": "MWUMVANEZA", "last": "Celestin"},
    {"name": "NDIMUBANZI", "last": "Gratien"},
    {"name": "RUKIMBIRA", "last": "Felicien"},
    {"name": "UZABAKILIHO", "last": "Pascal"},
    {"name": "ZIGAMA", "last": "Protais"},
    {"name": "NIYIGABA", "last": "Lambert"},
    {"name": "BAJENEZA", "last": "J Claude"},
    {"name": "GAKURU", "last": "J Robert"},
    {"name": "HABYALIMANA", "last": "Celestin"},
    {"name": "HAKIZIMANA", "last": "Felicien"},
    {"name": "HAVUGIMANA", "last": "Nathanael"},
    {"name": "IYAKAREMYE", "last": "James"},
    {"name": "KALIBUHUNGU", "last": "Augustin"},
    {"name": "MANIRAGABA", "last": "Valens"},
    {"name": "MUSABYEYEZU", "last": "Speciose"},
    {"name": "MUSABYIMANA", "last": "Cyprien"},
    {"name": "NIYODUSABA", "last": "Sam"},
    {"name": "RUYENZI", "last": "Charles"},
    {"name": "SIBOMANA", "last": "Janvier"},
    {"name": "UZABAKILIHO", "last": "Emmanuel"},
    {"name": "UZABAKILIHO", "last": "Innocent"},
    {"name": "SINGLE ESTATE", "last": "xxxxxx"},
    {"name": "BENIMANA", "last": "Evariste"},
    {"name": "BUHIGIRO", "last": "Leonard"},
    {"name": "BWANAKEYE", "last": "Cassien"},
    {"name": "HAKIZINKA", "last": "Felicien"},
    {"name": "HAKOLIMANA", "last": "Xavier"},
    {"name": "IYAMUREMYE", "last": "Jean"},
    {"name": "MBUZIHEREZO", "last": "Callixte"},
    {"name": "MUKAMUSONI", "last": "Veneranda"},
    {"name": "NTAMBARA", "last": "Daniel"},
    {"name": "NTEZIRYAYO", "last": "Alexandre"},
    {"name": "NYIRANDAME", "last": "Aurelie"},
    {"name": "NZABAMWITA", "last": "Anastase"},
    {"name": "UWIMANA", "last": "Seraphine"},
    {"name": "UWINGENEYE", "last": "Merise"},
    {"name": "UZABAKILIHO", "last": "Innocent"},
    {"name": "ZIHINJISHI", "last": "Laurence"},
    {"name": "RUTAYISIRE", "last": "J Pierre"},
    {"name": "SIBOMANA", "last": "J M Vianney"},
    {"name": "BAJENEZA", "last": "J Claude"},
    {"name": "BAZIHIZINA", "last": "Anastase"},
    {"name": "BIZIMANA", "last": "Assumani"},
    {"name": "KALIBUHUNGU", "last": "Augustin"},
    {"name": "MBYALIYEHE", "last": "J Bosco"},
    {"name": "RUYENZI", "last": "Charles"},
    {"name": "UBALIJORO", "last": "Xavier"},
    {"name": "ZILIMABAGABO", "last": "J Bosco"},
    {"name": "JIJUKA Cooperative", "last": "xxxxxx"},
    {"name": "BIRINDA", "last": "Faustin"},
    {"name": "HABIMANA", "last": "Evode"},
    {"name": "MUKANKUSI", "last": "Anastasie"},
    {"name": "MUNYAKARAGWE", "last": "Gabriel"},
    {"name": "MUNYAZESA", "last": "Charles"},
    {"name": "MWONGEREZA", "last": "Jean d'Amour"},
    {"name": "NZABONIMPA", "last": "J Baptiste"},
    {"name": "SINGLE ESTATE", "last": "xxxxxx"},
    {"name": "BUGENIMANA", "last": "Eric"},
    {"name": "BWANAKEYE", "last": "Cassien"},
    {"name": "GATSINZI", "last": "Anastase"},
    {"name": "HAKIZIMANA", "last": "Aloys"},
    {"name": "HAKIZIMANA", "last": "Innocent"},
    {"name": "IYAKAREMYE", "last": "James"},
    {"name": "MILINDI", "last": "Frank"},
    {"name": "MUKAMUSONI", "last": "Veneranda"},
    {"name": "MUNGANYINKA", "last": "Denise"},
    {"name": "MWONGEREZA", "last": "Jean d'Amour"},
    {"name": "NDABABONYE", "last": "Gervais"},
    {"name": "NIYODUSABA", "last": "Sam"},
    {"name": "NIYOYITA", "last": "xxxxxx"},
    {"name": "NTIGURIRWA", "last": "Sylvestre"},
    {"name": "RUGARAVU", "last": "Faustin"},
    {"name": "RUKIMBIRA", "last": "Felicien"},
    {"name": "UZABAKILIHO", "last": "Innocent"},
    {"name": "KAZIMBAYA", "last": "Christophe"},
    {"name": "KIMONYO", "last": "Augustin"},
    {"name": "RUKIMBIRA", "last": "Felicien"},
    {"name": "ZIGAMA", "last": "Protais"},
    {"name": "NIYIGABA", "last": "Lambert"},
    {"name": "BAJENEZA", "last": "J Claude"},
    {"name": "BWANAKEYE", "last": "Cassien"},
    {"name": "GATETE", "last": "J Bosco"},
    {"name": "NTASONI", "last": "Desire"},
    {"name": "NYIRAMAJORO", "last": "Xaverine"},
    {"name": "NYIRANDAME", "last": "Aurelie"},
    {"name": "NZABAMWITA", "last": "Anastase"},
    {"name": "NZABANDORA", "last": "Paulin"},
    {"name": "RWAMBONERA", "last": "Selvirien"},
    {"name": "RWAMPFIZI", "last": "Fidele"},
    {"name": "UBALIJORO", "last": "Xavier"},
    {"name": "UWIMANA", "last": "Seraphine"},
    {"name": "HABYALIMANA", "last": "Celestin"},
    {"name": "HAKIZIMANA", "last": "Innocent"},
    {"name": "HAKIZINKA", "last": "Felicien"},
    {"name": "KANYARWANDA", "last": "Faustin"},
    {"name": "MANIRAGABA", "last": "Valens"},
    {"name": "MBUZIHEREZO", "last": "Callixte"},
    {"name": "MBYALIYEHE", "last": "J Bosco"},
    {"name": "MILINDI", "last": "Frank"},
    {"name": "MUKAMANA", "last": "Jeannette"},
    {"name": "MUKAMUSONI", "last": "Veneranda"},
    {"name": "MWONGEREZA", "last": "Jean d'Amour"},
    {"name": "MWUMVANEZA", "last": "Celestin"},
    {"name": "NTEZIRYAYO", "last": "Alexandre"},
    {"name": "NYIRANZAYOMVUGWA", "last": "Fortunee"},
    {"name": "RUGARAVU", "last": "Faustin"},
    {"name": "UBALIJORO", "last": "Xavier"},
    {"name": "BIRINDA", "last": "Faustin"},
    {"name": "BUGENIMANA", "last": "Eric"},
    {"name": "BUHIGIRO", "last": "Leonard"},
    {"name": "GAKURU", "last": "J Robert"},
    {"name": "HAKIZIMANA", "last": "Innocent"},
    {"name": "MUNYAKAYANZA", "last": "Thelesphore"},
    {"name": "NSABIMANA", "last": "Alphonse"},
    {"name": "NTAMBARA", "last": "Daniel"},
    {"name": "NZABONIMPA", "last": "J Baptiste"},
    {"name": "RWAMPFIZI", "last": "Fidele"},
    {"name": "RUTAYISIRE", "last": "J Pierre"},
    {"name": "SIBOMANA", "last": "J M Vianney"},
    {"name": "JIJUKA Cooperative", "last": "xxxxxx"},
    {"name": "BENIMANA", "last": "Evariste"},
    {"name": "BIZIMANA", "last": "Assumani"},
    {"name": "BUTARE", "last": "Fidele"},
    {"name": "HAKOLIMANA", "last": "Xavier"},
    {"name": "IYAMUREMYE", "last": "Jean"},
    {"name": "KALIBUHUNGU", "last": "Augustin"},
    {"name": "KWINDIRI (2)", "last": "xxxxxx"},
    {"name": "MBUZIHEREZO", "last": "Callixte"},
    {"name": "MUNYAKAYANZA", "last": "Thelesphore"},
    {"name": "MUSABYEYEZU", "last": "Speciose"},
    {"name": "RUYENZI", "last": "Charles"},
    {"name": "SIBOMANA", "last": "Janvier"},
    {"name": "UWIMANA", "last": "Seraphine"},
    {"name": "UZABAKILIHO", "last": "Innocent"},
    {"name": "UZABAKILIHO", "last": "Pascal"},
    {"name": "ZILIMABAGABO", "last": "J Bosco"},
    {"name": "BWANAKEYE", "last": "Cassien"},
    {"name": "KALIBUHUNGU", "last": "Augustin"},
    {"name": "KAZIMBAYA", "last": "Christophe"},
    {"name": "KWINDIRI", "last": "xxxxxx"},
    {"name": "MUHUTU", "last": "Jean"},
    {"name": "MUKESHIMANA", "last": "xxxxxx"},
    {"name": "MUKURALINDA", "last": "Innocent"},
    {"name": "MUNGANYINKA", "last": "Denise"},
    {"name": "NZABANDORA", "last": "Paulin"},
    {"name": "RUYENZI", "last": "Charles"},
    {"name": "RWAMBONERA", "last": "Selvirien"},
    {"name": "UWIMANA", "last": "Seraphine"},
    {"name": "UZABAKILIHO", "last": "Emmanuel"},
    {"name": "BENIMANA", "last": "Evariste"},
    {"name": "KALIBUHUNGU", "last": "Augustin"},
    {"name": "KALISA", "last": "J Damascene"},
    {"name": "KIMONYO", "last": "Augustin"},
    {"name": "MBYALIYEHE", "last": "J Bosco"},
    {"name": "MUNYAZESA", "last": "Charles"},
    {"name": "NDOLIYOBIJYA", "last": "Joseph"},
    {"name": "NTIGURIRWA", "last": "Sylvestre"},
    {"name": "RUGARAVU", "last": "Faustin"},
    {"name": "UWIZEYIMANA", "last": "Felicien"},
    {"name": "UZABAKILIHO", "last": "Innocent"},
    {"name": "ZILIMABAGABO", "last": "J Bosco"},
    {"name": "SINGLE ESTATE", "last": "xxxxxx"},
    {"name": "AYIRWANDA", "last": "Frederick"},
    {"name": "BAJENEZA", "last": "J Claude"},
    {"name": "MILINDI", "last": "Frank"},
    {"name": "MUKAMANA", "last": "Jeannette"},
    {"name": "MUSESARUGAMBA", "last": "Francois"},
    {"name": "MUTSINZI", "last": "Andre"},
    {"name": "UWINGENEYE", "last": "Merise"},
    {"name": "SINGLE ESTATE", "last": "xxxxxx"},
    {"name": "NIYIGABA", "last": "Lambert"},
    {"name": "BAJENEZA", "last": "J Claude"},
    {"name": "HABYALIMANA", "last": "Celestin"},
    {"name": "HAKIZIMANA", "last": "Innocent"},
    {"name": "HAVUGIMANA", "last": "Nathanael"},
    {"name": "MUKAMUSONI", "last": "Veneranda"},
    {"name": "NZABAMWITA", "last": "Anastase"},
    {"name": "SINGLE ESTATE", "last": "xxxxxx"},
    {"name": "NIYIGABA", "last": "Lambert"},
    {"name": "BENIMANA", "last": "Evariste"},
    {"name": "BUTARE", "last": "Fidele"},
    {"name": "HAKIZINKA", "last": "Felicien"},
    {"name": "MUNYAKARAGWE", "last": "Gabriel"},
    {"name": "MUSABYEYEZU", "last": "Speciose"},
    {"name": "NZABAMWITA", "last": "Anastase"},
    {"name": "UZABAKILIHO", "last": "Pascal"},
    {"name": "BIRINDA", "last": "Faustin"},
    {"name": "GATETE", "last": "J Bosco"},
    {"name": "HAKIZIMANA", "last": "Aloys"},
    {"name": "IYAKAREMYE", "last": "James"},
    {"name": "MWONGEREZA", "last": "Jean d'Amour"},
    {"name": "NDABABONYE", "last": "Gervais"},
    {"name": "NSABIMANA", "last": "Alphonse"},
    {"name": "NTIGURIRWA", "last": "Sylvestre"},
    {"name": "NYIRAMAJORO", "last": "Xaverine"},
    {"name": "RUGARAVU", "last": "Faustin"},
    {"name": "IYAMUREMYE", "last": "Jean"},
    {"name": "KALISA", "last": "J Damascene"},
    {"name": "KANYARWANDA", "last": "Faustin"},
    {"name": "MUHUTU", "last": "Jean"},
    {"name": "MUKESHIMANA", "last": "xxxxxx"},
    {"name": "MUKURALINDA", "last": "Innocent"},
    {"name": "MUSABYIMANA", "last": "Cyprien"},
    {"name": "MWONGEREZA", "last": "Jean d'Amour"},
    {"name": "NTEZIRYAYO", "last": "Alexandre"},
    {"name": "NYIRAMAJORO", "last": "Xaverine"},
    {"name": "NYIRANDAME", "last": "Aurelie"},
    {"name": "NZABONIMPA", "last": "J Baptiste"},
    {"name": "RWAMBONERA", "last": "Selvirien"},
    {"name": "RWAMPFIZI", "last": "Fidele"},
    {"name": "UWIMANA", "last": "Seraphine"},
    {"name": "UZABAKILIHO", "last": "Pascal"},
    {"name": "SINGLE ESTATE", "last": "xxxxxx"},
    {"name": "JIJUKA Cooperative", "last": "xxxxxx"},
    {"name": "BWANAKEYE", "last": "Cassien"},
    {"name": "MUKAMUSONI", "last": "Veneranda"},
    {"name": "MWUMVANEZA", "last": "Celestin"},
    {"name": "RUYENZI", "last": "Charles"},
    {"name": "ZIGAMA", "last": "Protais"},
    {"name": "HAKIZIMANA", "last": "Innocent"},
    {"name": "MBYALIYEHE", "last": "J Bosco"},
    {"name": "MUKAMANA", "last": "Jeannette"},
    {"name": "MUKANKUSI", "last": "Anastasie"},
    {"name": "MUNGANYINKA", "last": "Denise"},
    {"name": "NDIMUBANZI", "last": "Gratien"},
    {"name": "NTAMBARA", "last": "Daniel"},
    {"name": "NYIRAKAMANA", "last": "Annonciata"},
    {"name": "UZABAKILIHO", "last": "Innocent"},
    {"name": "SINGLE ESTATE", "last": "xxxxxx"},
]

# for farmer in farmers:
#     try:
#         obj = Farmer.objects.get(
#             first_name__iexact=farmer["name"].title(),
#             last_name__iexact=farmer["last"].title(),
#         )
#         print(obj.idencode)
#     except Exception:
#         print("*************couldnt find ", farmer)
