# Generated by Django 2.2.6 on 2021-03-14 18:05
import django.contrib.postgres.fields.jsonb
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
                ("visibility", models.BooleanField(default=True)),
                ("title_en", models.CharField(default="", max_length=300)),
                (
                    "title_loc",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("body_en", models.CharField(default="", max_length=500)),
                (
                    "body_loc",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "action_url",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "action",
                    models.IntegerField(
                        choices=[
                            (1, "Normal"),
                            (2, "Email"),
                            (3, "Push notification"),
                            (4, "Push and email"),
                            (5, "Push, email and SMS"),
                            (6, "Email and SMS"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "event",
                    models.IntegerField(
                        choices=[
                            (1, "User"),
                            (2, "Validation Token"),
                            (3, "Node"),
                            (4, "Node Member"),
                            (5, "Node Document"),
                            (6, "Invitation"),
                            (7, "External Transaction"),
                            (8, "Internal Transaction"),
                            (9, "Attached Claim"),
                            (10, "Batch Comment"),
                            (12, "Transaction Claim"),
                            (11, "Transaction Request"),
                            (14, "Claim Request"),
                            (15, "Information Request"),
                            (16, "Connection Request"),
                            (17, "FFAdmin Invitation"),
                        ],
                        default=0,
                    ),
                ),
                ("event_id", models.CharField(default="", max_length=50)),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (5, "Verify email"),
                            (7, "Reset password email"),
                            (8, "Magic login email"),
                            (9, "Invited as member"),
                            (10, "Node Invite"),
                            (32, "FFAdmin Invite"),
                            (33, "FFAdmin Existing Node Invite"),
                            (11, "Email Change"),
                            (12, "Existing Node Invite"),
                            (30, "Week One Reminder"),
                            (31, "Week Two Reminder"),
                            (13, "Received stock"),
                            (14, "Sent stock"),
                            (15, "Transaction Rejected"),
                            (16, "Received Stock Request"),
                            (17, "Decline Stock Request"),
                            (22, "Received Claim Request"),
                            (23, "Decline Claim Request"),
                            (24, "Received Information Request"),
                            (25, "Decline Information Request"),
                            (26, "Received Connection Request"),
                            (18, "Received verification Request"),
                            (19, "Approved claim"),
                            (20, "Rejected claim"),
                            (21, "Added comment"),
                            (27, "Decline Connection Request"),
                            (28, "Received Information Response"),
                            (29, "Received Claim Response"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "context",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, null=True
                    ),
                ),
                (
                    "send_to",
                    models.EmailField(
                        blank=True, default="", max_length=254, null=True
                    ),
                ),
            ],
            options={
                "ordering": ("-created_on",),
            },
        ),
    ]
