# Generated by Django 2.2.6 on 2023-05-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_auto_20230202_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event',
            field=models.IntegerField(choices=[(1, 'User'), (2, 'Validation Token'), (3, 'Node'), (4, 'Node Member'), (5, 'Node Document'), (6, 'Invitation'), (7, 'External Transaction'), (8, 'Internal Transaction'), (9, 'Attached Claim'), (10, 'Batch Comment'), (12, 'Transaction Claim'), (11, 'Transaction Request'), (14, 'Claim Request'), (15, 'Information Request'), (16, 'Connection Request'), (16, 'Connection Request'), (18, 'Node Card History')], default=0),
        ),
    ]
