STOCK = 1
EXTERNAL_TRANSACTION = 2
INTERNAL_TRANSACTION = 3
CONNECTIONS = 4
FARMER = 5
COMPANY = 6
ADMIN_COMPANY = 7
ADMIN_FARMER = 8
ADMIN_EXTERNAL_TRANSACTION = 9
PAYMENTS = 10

EXPORT_TYPE_CHOICES = [
    (STOCK, "STOCK"),
    (EXTERNAL_TRANSACTION, "EXTERNAL_TRANSACTION"),
    (INTERNAL_TRANSACTION, "INTERNAL_TRANSACTION"),
    (CONNECTIONS, "CONNECTIONS"),
    (FARMER, "FARMER"),
    (COMPANY, "COMPANY"),
    (ADMIN_COMPANY, "ADMIN_COMPANY"),
    (ADMIN_FARMER, "ADMIN_FARMER"),
    (ADMIN_EXTERNAL_TRANSACTION, "ADMIN_EXTERNAL_TRANSACTION"),
    (PAYMENTS, "PAYMENTS"),
]

EXCEL = 1
CSV = 2

FILE_TYPE_CHOICES = [
    (EXCEL, ".xlsx"),
    (CSV, ".csv"),
]

PENDING = "PEND"
COMPLETED = "DONE"
REVOKED = "RVKD"
FAILED = "FAIL"

STATUS_CHOICES = [
    (PENDING, "PENDING"),
    (COMPLETED, "COMPLETED"),
    (REVOKED, "REVOKED"),
    (FAILED, "FAILED"),
]
